---
- name: Add authorized keys
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ item }}"
  with_items: "{{ system_security_autorizedkeys }}"
  tags:
    - setup-all
    - security-ssh
    - rotate-ssh-keys

- name: Revoke authorized keys
  authorized_key:
    user: "{{ ansible_user }}"
    state: absent
    key: "{{ item }}"
  with_items: "{{ system_security_notautorizedkeys }}"
  tags:
    - setup-all
    - security-ssh
    - rotate-ssh-keys

- name: Enforce sshd config
  template:
    src: etc/ssh/sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0644
    owner: root
    group: root
  register: system_security_sshd_config

- name: Reload sshd configuration
  service:
    name: sshd
    state: reloaded
  when: system_security_sshd_config.changed
