---
- name: Install ufw
  package:
    name: ufw
    state: present

- name: Ensure ufw stared and running
  service:
    state: started
    enabled: yes
    name: ufw

- name: Apply rules
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.name }}"
  with_items: "{{ system_security_ufw_rules }}"

- name: Allow email receiving
  ufw:
    rule: allow
    port: '25'
    proto: tcp
    comment: email2matrix
  when: matrix_email2matrix_enabled|bool

- name: Allow heisenbridge identd
  ufw:
    rule: allow
    port: '113'
    proto: tcp
    comment: heisenbridge/identd
  when: matrix_heisenbridge_enabled|bool

- name: Allow wireguard
  ufw:
    rule: allow
    port: "{{ custom_wireguard_port }}"
    proto: udp
    comment: wireguard server
  when: custom_wireguard_enabled|bool

- name: Allow wireguard network
  ufw:
    rule: allow
    interface: "{{ custom_wireguard_interface }}"
    direction: in
    proto: any
  when: custom_wireguard_enabled|bool

- name: Allow dnsmasq (UDP)
  ufw:
    rule: allow
    port: "{{ custom_dnsmasq_port }}"
    proto: udp
    comment: dnsmasq
  when: custom_dnsmasq_enabled|bool

- name: Allow dnsmasq (TCP)
  ufw:
    rule: allow
    port: "{{ custom_dnsmasq_port }}"
    proto: tcp
    comment: dnsmasq
  when: custom_dnsmasq_enabled|bool

- name: Start ufw
  ufw:
    logging: 'on'
    policy: deny
    state: enabled
