---

- name: Ensure int-prometheus-blackbox-exporter path exist
  ansible.builtin.file:
    path: "{{ int_prometheus_blackbox_exporter_config_path }}"
    state: directory
    mode: 0750
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"

- name: Ensure int-prometheus-blackbox-exporter config file created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/config.yml.j2"
    dest: "{{ int_prometheus_blackbox_exporter_config_path }}/config.yml"
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
    mode: 0640

- name: Ensure int-prometheus-blackbox-exporter image is pulled
  community.docker.docker_image:
    name: "{{ int_prometheus_blackbox_exporter_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ int_prometheus_blackbox_exporter_docker_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else int_prometheus_blackbox_exporter_docker_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure int-prometheus-blackbox-exporter.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/int-prometheus-blackbox-exporter.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/int-prometheus-blackbox-exporter.service"
    mode: 0644
