stages:
  - release

base:
  stage: release
  when: manual
  services:
    - docker:dind
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/jdrouet/docker-with-buildx:stable
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker buildx create --use
    - docker buildx build --platform linux/arm64/v8,linux/amd64 --push -t ${CI_REGISTRY_IMAGE}/base -t registry.etke.cc/etke.cc/ansible/base -f Dockerfile.base .
  tags:
    - docker

fresh:
  stage: release
  only: ['fresh']
  services:
    - docker:dind
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/jdrouet/docker-with-buildx:stable
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker buildx create --use
    - docker buildx build --platform linux/arm64/v8,linux/amd64 --push -t $CI_REGISTRY_IMAGE:fresh -t registry.etke.cc/etke.cc/ansible:fresh .
  tags:
    - docker

sync images:
  stage: release
  only: ['fresh']
  needs: ['fresh']
  dependencies: ['fresh']
  image: $CI_REGISTRY_IMAGE:fresh
  before_script:
    - cp -r /playbook/.config/inventory /
  script:
    - cd /playbook; ansible-playbook play/all.yml -l localhost -t skopeo -e target=localhost
  allow_failure: true

stable:
  stage: release
  only: ['master']
  services:
    - docker:dind
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/jdrouet/docker-with-buildx:stable
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker buildx create --use
    - docker buildx build --platform linux/arm64/v8,linux/amd64 --push -t $CI_REGISTRY_IMAGE -t registry.etke.cc/etke.cc/ansible .
  tags:
    - docker
