FROM alpine:3.16.1
ARG ANSIBLE_CORE=2.13.2
ARG ANSIBLE=6.1.0

RUN apk --no-cache add python3 && \
		apk --no-cache add --virtual builddeps alpine-sdk py3-cffi py3-pip && \
		pip install ansible-core==${ANSIBLE_CORE} ansible==${ANSIBLE} && \
		pip cache purge && \
		apk del builddeps && \
		rm -rf /var/cache/apk/* && \
		rm -rf /root/.cache/pip && \
		find / -name '*.pyc' -exec rm {} \;
