---

- include: upstream/requirements.yml
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-cleanup.git
  version: main
  name: cleanup
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-fail2ban.git
  version: main
  name: fail2ban
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-firezone.git
  version: v0.7.36-1
  name: firezone
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-funkwhale.git
  version: v1.4.0-5
  name: funkwhale
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-gotosocial.git
  version: v0.17.0-0
  name: gotosocial
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-languagetool.git
  version: v6.5-0
  name: languagetool
- src: git+https://github.com/kinduff/ansible-docker-linkding.git
  version: v1.9.0
  name: linkding
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-miniflux.git
  version: v2.2.1-0
  name: miniflux
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-peertube.git
  version: v6.3.2-0
  name: peertube
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-radicale.git
  version: v3.3.0.0-0
  name: radicale
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-ssh.git
  version: main
  name: ssh
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-swap.git
  version: main
  name: swap
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-ufw.git
  version: main
  name: ufw
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-uptime_kuma.git
  version: v1.23.15-0
  name: uptime_kuma
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-vaultwarden.git
  version: v1.32.2-0
  name: vaultwarden
