---

- include: upstream/requirements.yml
- src: git+https://gitlab.com/etke.cc/roles/cleanup.git
  version: main
- src: git+https://gitlab.com/etke.cc/roles/fail2ban.git
  version: main
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-firezone.git
  version: v0.7.35-7
  name: firezone
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-funkwhale.git
  version: v1.4.0-3
  name: funkwhale
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-gotosocial.git
  version: v0.15.0-0
  name: gotosocial
- src: git+https://gitlab.com/etke.cc/roles/languagetool.git
  version: v6.3-1
- src: git+https://github.com/kinduff/ansible-docker-linkding.git
  version: v1.9.0
  name: linkding
- src: git+https://gitlab.com/etke.cc/roles/miniflux.git
  version: v2.1.2-0
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-peertube.git
  version: v6.0.4-0
  name: peertube
- src: git+https://gitlab.com/etke.cc/roles/radicale.git
  version: v3.1.9.1-0
- src: git+https://gitlab.com/etke.cc/roles/ssh.git
  version: main
- src: git+https://gitlab.com/etke.cc/roles/swap.git
  version: main
- src: git+https://gitlab.com/etke.cc/roles/ufw.git
  version: main
- src: git+https://gitlab.com/etke.cc/roles/uptime_kuma.git
  version: v1.23.11-0
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-vaultwarden.git
  version: v1.30.5-1
  name: vaultwarden
