---

- include: upstream/requirements.yml
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-cleanup.git
  version: main
  name: cleanup
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-fail2ban.git
  version: main
  name: fail2ban
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-firezone.git
  version: v0.7.36-6
  name: firezone
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-funkwhale.git
  version: v1.4.0-11
  name: funkwhale
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-gotosocial.git
  version: v0.19.1-6
  name: gotosocial
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-languagetool.git
  version: v6.6-2
  name: languagetool
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-linkding.git
  version: v1.41.0-4
  name: linkding
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-miniflux.git
  version: v2.2.10-2
  name: miniflux
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-peertube.git
  version: v7.2.3-2
  name: peertube
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-radicale.git
  version: v3.5.4.0-2
  name: radicale
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-ssh.git
  version: main
  name: ssh
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-swap.git
  version: main
  name: swap
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-ufw.git
  version: main
  name: ufw
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-uptime_kuma.git
  version: v1.23.16-7
  name: uptime_kuma
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-vaultwarden.git
  version: v1.34.1-4
  name: vaultwarden
