---

- include: upstream/requirements.yml
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-cleanup.git
  version: v1.0.0-0
  name: cleanup
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-fail2ban.git
  version: main
  name: fail2ban
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-firezone.git
  version: v0.7.36-7
  name: firezone
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-funkwhale.git
  version: v1.4.1-2
  name: funkwhale
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-gotosocial.git
  version: v0.20.3-1
  name: gotosocial
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-languagetool.git
  version: v6.7-0
  name: languagetool
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-linkding.git
  version: v1.45.0-1
  name: linkding
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-miniflux.git
  version: v2.2.17-1
  name: miniflux
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-peertube.git
  version: v7.2.3-6
  name: peertube
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-radicale.git
  version: v3.6.0.0-1
  name: radicale
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-ssh.git
  version: main
  name: ssh
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-swap.git
  version: main
  name: swap
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-ufw.git
  version: main
  name: ufw
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-uptime_kuma.git
  version: v1.23.17-3
  name: uptime_kuma
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-vaultwarden.git
  version: v1.35.3-1
  name: vaultwarden
