---

- include: upstream/requirements.yml
- src: git+https://gitlab.com/etke.cc/roles/cleanup.git
  version: main
- src: git+https://gitlab.com/etke.cc/roles/fail2ban.git
  version: main
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-gotosocial.git
  version: v0.11.0-1
  name: gotosocial
- src: git+https://gitlab.com/etke.cc/roles/languagetool.git
  version: v6.1-0
- src: git+https://gitlab.com/etke.cc/roles/miniflux.git
  version: v2.0.49-0
- src: git+https://gitlab.com/etke.cc/roles/radicale.git
  version: v3.1.8.3-0
- src: git+https://gitlab.com/etke.cc/roles/ssh.git
  version: main
- src: git+https://gitlab.com/etke.cc/roles/swap.git
  version: main
- src: git+https://gitlab.com/etke.cc/roles/ufw.git
  version: main
- src: git+https://gitlab.com/etke.cc/roles/uptime_kuma.git
  version: v1.23.3-0
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-vaultwarden.git
  version: v1.29.2-2
  name: vaultwarden
