- src: git+https://gitlab.com/etke.cc/roles/swap.git
  version: main
- src: git+https://gitlab.com/etke.cc/roles/ufw.git
  version: main
- src: git+https://gitlab.com/etke.cc/roles/ssh.git
  version: main
- src: git+https://gitlab.com/etke.cc/roles/fail2ban.git
  version: main
- src: git+https://gitlab.com/etke.cc/roles/cleanup.git
  version: main
- src: git+https://gitlab.com/etke.cc/roles/languagetool.git
  version: v6.0-3
- src: git+https://gitlab.com/etke.cc/roles/miniflux.git
  version: v2.0.43-1
- src: git+https://gitlab.com/etke.cc/roles/prometheus_blackbox_exporter.git
  version: v0.23.0-0
- src: git+https://gitlab.com/etke.cc/roles/radicale.git
  version: v3.1.8.1-1
- src: git+https://gitlab.com/etke.cc/roles/uptime_kuma.git
  version: v1.21.0-0
