---

# Roles need to be in public repositories
# or `ansible-galaxy install` as part of container image building will fail.
#
# Cloning via https (not ssh), because ssh may not be available in the container.

- src: git+https://gitlab.com/etke.cc/roles/docker.git
  version: main
- src: git+https://gitlab.com/etke.cc/roles/swap.git
  version: main
- src: git+https://gitlab.com/etke.cc/roles/security.git
  version: main
- src: git+https://gitlab.com/etke.cc/roles/cleanup.git
  version: main
- src: git+https://gitlab.com/etke.cc/roles/languagetool.git
  version: v6.0-0
