---

- include: upstream/requirements.yml
- src: git+https://gitlab.com/etke.cc/roles/cleanup.git
  version: main
- src: git+https://gitlab.com/etke.cc/roles/fail2ban.git
  version: main
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-gotosocial.git
  version: v0.8.1-0
  name: gotosocial
- src: git+https://gitlab.com/etke.cc/roles/languagetool.git
  version: v6.1-0
- src: git+https://gitlab.com/etke.cc/roles/miniflux.git
  version: v2.0.44-0
- src: git+https://gitlab.com/etke.cc/roles/radicale.git
  version: v3.1.8.2-2
- src: git+https://gitlab.com/etke.cc/roles/soft_serve.git
  version: v0.4.7-0
- src: git+https://gitlab.com/etke.cc/roles/ssh.git
  version: main
- src: git+https://gitlab.com/etke.cc/roles/swap.git
  version: main
- src: git+https://gitlab.com/etke.cc/roles/ufw.git
  version: main
- src: git+https://gitlab.com/etke.cc/roles/uptime_kuma.git
  version: v1.21.2-0
