---
# synapse_auto_compressor tool
# Project source code URL: https://github.com/matrix-org/rust-synapse-compress-state

matrix_synapse_auto_compressor_enabled: true

matrix_synapse_auto_compressor_container_image_self_build: false
matrix_synapse_auto_compressor_docker_repo: "https://gitlab.com/etke.cc/rust-synapse-compress-state.git"
matrix_synapse_auto_compressor_docker_repo_version: "{{ 'main' if matrix_synapse_auto_compressor_version == 'latest' else matrix_synapse_auto_compressor_version }}"
matrix_synapse_auto_compressor_docker_src_files_path: "{{ matrix_synapse_auto_compressor_base_path }}"

matrix_synapse_auto_compressor_version: v0.1.3
matrix_synapse_auto_compressor_docker_image: "{{ matrix_synapse_auto_compressor_docker_image_name_prefix }}etke.cc/rust-synapse-compress-state:{{ matrix_synapse_auto_compressor_version }}"
matrix_synapse_auto_compressor_docker_image_name_prefix: "{{ 'localhost/' if matrix_synapse_auto_compressor_container_image_self_build else 'registry.gitlab.com/' }}"
matrix_synapse_auto_compressor_docker_image_force_pull: "{{ matrix_synapse_auto_compressor_docker_image.endswith(':latest') }}"

matrix_synapse_auto_compressor_base_path: "{{ matrix_base_data_path }}/synapse-auto-compressor"

# A list of extra arguments to pass to the container
matrix_synapse_auto_compressor_container_extra_arguments: []

# List of systemd services that matrix-synapse-auto-compressor.service depends on
matrix_synapse_auto_compressor_systemd_required_services_list: ['docker.service']

# List of systemd services that matrix-synapse-auto-compressor.service wants
matrix_synapse_auto_compressor_systemd_wanted_services_list: []

matrix_synapse_auto_compressor_database_username: 'synapse'
matrix_synapse_auto_compressor_database_password: 'some-password'
matrix_synapse_auto_compressor_database_hostname: ''
matrix_synapse_auto_compressor_database_port: 5432
matrix_synapse_auto_compressor_database_name: 'synapse'

# connection string to synapse database (postgres only)
matrix_synapse_auto_compressor_synapse_database: 'postgres://{{ matrix_synapse_auto_compressor_database_username }}:{{ matrix_synapse_auto_compressor_database_password }}@{{ matrix_synapse_auto_compressor_database_hostname }}:{{ matrix_synapse_auto_compressor_database_port }}/{{ matrix_synapse_auto_compressor_database_name }}'

# systemd calendar configuration for the compressor job
matrix_synapse_auto_compressor_calendar: "*-*-* 00:00:00"

# The number of state groups to work on at once.
# All of the entries from state_groups_state are requested from the database for state groups that are worked on.
# Therefore small chunk sizes may be needed on machines with low memory.
# Note: if the compressor fails to find space savings on the chunk as a whole
# (which may well happen in rooms with lots of backfill in) then the entire chunk is skipped.
matrix_synapse_auto_compressor_chunk_size: 500

# CHUNKS_TO_COMPRESS chunks of size CHUNK_SIZE will be compressed.
# The higher this number is set to, the longer the compressor will run for.
matrix_synapse_auto_compressor_chunks_to_compress: 100

# Sizes of each new level in the compression algorithm, as a comma-separated list.
# The first entry in the list is for the lowest, most granular level, with each subsequent entry being for the next highest level.
# The number of entries in the list determines the number of levels that will be used.
# The sum of the sizes of the levels affects the performance of fetching the state from the database,
# as the sum of the sizes is the upper bound on the number of iterations needed to fetch a given set of state.
matrix_synapse_auto_compressor_levels: "100,50,25"

matrix_synapse_auto_compressor_command: "synapse_auto_compressor -p {{ matrix_synapse_auto_compressor_synapse_database }} -c {{ matrix_synapse_auto_compressor_chunk_size }} -n {{ matrix_synapse_auto_compressor_chunks_to_compress }} -d {{ matrix_synapse_auto_compressor_levels }}"
