---
- name: Update packages list
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Install ufw
  apt:
    name: ufw

- name: Ensure ufw stared and running
  systemd:
    state: started
    enabled: yes
    name: ufw
