---
- name: Install ufw
  package:
    name: ufw
    state: present

- name: Ensure ufw stared and running
  service:
    state: started
    enabled: yes
    name: ufw

- name: Apply rules
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.name }}"
  with_items: "{{ system_security_ufw_rules }}"

- name: Start ufw
  ufw:
    logging: 'on'
    policy: deny
    state: enabled
