---
- name: Assume parent's defaults from a predefined file
  ansible.builtin.include_vars: parent.yml
  when: matrix_nginx_proxy_website_enabled|bool and matrix_nginx_proxy_base_path is not defined
  tags:
    - setup-all
    - setup-website
    - install-all
    - install-website

- name: Clone website repo
  ansible.builtin.git:
    depth: 1
    force: true
    accept_newhostkey: true
    repo: "{{ matrix_nginx_proxy_website_repo }}"
    dest: "{{ matrix_nginx_proxy_website_tmp_path }}/nginx-proxy-website_{{ inventory_hostname }}"
    version: "{{ matrix_nginx_proxy_website_repo_ref }}"
  delegate_to: 127.0.0.1
  become: false
  when: matrix_nginx_proxy_website_enabled|bool
  tags:
    - setup-all
    - setup-website
    - install-all
    - install-website

- name: Build website
  ansible.builtin.command: "{{ item }}"
  args:
    chdir: "{{ matrix_nginx_proxy_website_tmp_path }}/nginx-proxy-website_{{ inventory_hostname }}"
  delegate_to: 127.0.0.1
  become: false
  when: matrix_nginx_proxy_website_enabled|bool
  with_items: "{{ matrix_nginx_proxy_website_commands }}"
  tags:
    - setup-all
    - setup-website
    - install-all
    - install-website

- name: Cleanup build directory before deploy
  ansible.builtin.file:
    state: absent
    path: "{{ matrix_nginx_proxy_website_tmp_path }}/nginx-proxy-website_{{ inventory_hostname }}/{{ matrix_nginx_proxy_website_dist }}/{{ item }}"
  with_items: "{{ matrix_nginx_proxy_website_exclude }}"
  delegate_to: 127.0.0.1
  become: false
  when: matrix_nginx_proxy_website_enabled|bool
  tags:
    - setup-all
    - setup-website
    - install-all
    - install-website

- name: Create website artifact
  community.general.archive:
    format: tar
    force_archive: true
    path: "{{ matrix_nginx_proxy_website_tmp_path }}/nginx-proxy-website_{{ inventory_hostname }}/{{ matrix_nginx_proxy_website_dist }}/"
    dest: "{{ matrix_nginx_proxy_website_tmp_path }}/nginx-proxy-website_{{ inventory_hostname }}/artifact.tar"
    mode: 0644
  delegate_to: 127.0.0.1
  become: false
  when: matrix_nginx_proxy_website_enabled|bool
  tags:
    - setup-all
    - setup-website
    - install-all
    - install-website

- name: Deploy website
  ansible.builtin.unarchive:
    src: "{{ matrix_nginx_proxy_website_tmp_path }}/nginx-proxy-website_{{ inventory_hostname }}/artifact.tar"
    dest: "{{ matrix_nginx_proxy_website_path }}"
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
  when: matrix_nginx_proxy_website_enabled|bool
  tags:
    - setup-all
    - setup-website
    - install-all
    - install-website

- name: Remove temporary build dir
  ansible.builtin.file:
    state: absent
    path: "{{ matrix_nginx_proxy_website_tmp_path }}/nginx-proxy-website_{{ inventory_hostname }}"
  delegate_to: 127.0.0.1
  become: false
  when: matrix_nginx_proxy_website_enabled|bool
  tags:
    - setup-all
    - setup-website
    - install-all
    - install-website
