---
- include_vars: parent.yml
  when: matrix_nginx_proxy_website_enabled|bool and matrix_nginx_proxy_base_path is not defined
  tags:
    - setup-all
    - setup-website

- name: Clone website repo
  git:
    depth: 1
    force: yes
    accept_newhostkey: yes
    repo: "{{ matrix_nginx_proxy_website_repo }}"
    dest: "{{ matrix_nginx_proxy_website_tmp_path }}/nginx-proxy-website_{{ inventory_hostname }}"
    version: "{{ matrix_nginx_proxy_website_repo_ref }}"
  delegate_to: 127.0.0.1
  become: no
  when: matrix_nginx_proxy_website_enabled|bool
  tags:
    - setup-all
    - setup-website

- name: Build website
  command: "{{ item }}"
  args:
    chdir: "{{ matrix_nginx_proxy_website_tmp_path }}/nginx-proxy-website_{{ inventory_hostname }}"
  delegate_to: 127.0.0.1
  become: no
  when: matrix_nginx_proxy_website_enabled|bool
  with_items: "{{ matrix_nginx_proxy_website_commands }}"
  tags:
    - setup-all
    - setup-website

- name: Cleanup build directory before deploy
  file:
    state: absent
    path: "{{ matrix_nginx_proxy_website_tmp_path }}/nginx-proxy-website_{{ inventory_hostname }}/{{ matrix_nginx_proxy_website_dist }}/{{ item }}"
  with_items: "{{ matrix_nginx_proxy_website_exclude }}"
  delegate_to: 127.0.0.1
  become: no
  when: matrix_nginx_proxy_website_enabled|bool
  tags:
    - setup-all
    - setup-website

- name: Create website artifact
  archive:
    format: tar
    force_archive: yes
    path: "{{ matrix_nginx_proxy_website_tmp_path }}/nginx-proxy-website_{{ inventory_hostname }}/{{ matrix_nginx_proxy_website_dist }}/"
    dest: "{{ matrix_nginx_proxy_website_tmp_path }}/nginx-proxy-website_{{ inventory_hostname }}/artifact.tar"
  delegate_to: 127.0.0.1
  become: no
  when: matrix_nginx_proxy_website_enabled|bool
  tags:
    - setup-all
    - setup-website

- name: Deploy website
  unarchive:
    src: "{{ matrix_nginx_proxy_website_tmp_path }}/nginx-proxy-website_{{ inventory_hostname }}/artifact.tar"
    dest: "{{ matrix_nginx_proxy_website_path }}"
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
  when: matrix_nginx_proxy_website_enabled|bool
  tags:
    - setup-all
    - setup-website

- name: Remove temporary build dir
  file:
    state: absent
    path: "{{ matrix_nginx_proxy_website_tmp_path }}/nginx-proxy-website_{{ inventory_hostname }}"
  delegate_to: 127.0.0.1
  become: no
  when: matrix_nginx_proxy_website_enabled|bool
  tags:
    - setup-all
    - setup-website
