---
- name: Init
  ansible.builtin.import_tasks: init.yml
  tags:
    - always

- name: Install
  ansible.builtin.import_tasks: install.yml
  when: custom_wireguard_enabled|bool
  tags:
    - setup-all
    - setup-wireguard

- name: Uninstall
  ansible.builtin.import_tasks: uninstall.yml
  when: not custom_wireguard_enabled|bool
  tags:
    - setup-all
    - setup-wireguard
