---
- import_tasks: init.yml
  tags:
    - always

- import_tasks: install.yml
  when: custom_wireguard_enabled|bool
  tags:
    - setup-all
    - setup-wireguard

- import_tasks: uninstall.yml
  when: not custom_wireguard_enabled|bool
  tags:
    - setup-all
    - setup-wireguard
