---

- block:
    - when: custom_wireguard_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-wireguard
    - install-all
    - install-wireguard

- block:
    - when: not custom_wireguard_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-wireguard
