---
- name: Check existence of wg-quick@ service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/wg-quick@.service"
  register: custom_wireguard_service_stat

- name: Ensure wireguard service stopped
  ansible.builtin.service:
    name: "wg-quick@{{ custom_wireguard_interface }}"
    enabled: false
    state: stopped
  ignore_errors: true # it fails if not installed because of @interface part, seems like different approach to such services on ansible side
  when: "custom_wireguard_service_stat.stat.exists|bool"

- name: Ensure wireguard configuration removed
  ansible.builtin.file:
    path: "{{ custom_wireguard_path }}"
    state: absent
  when: "custom_wireguard_service_stat.stat.exists|bool"

- name: Ensure wireguard packages removed
  ansible.builtin.package:
    name: wireguard-tools
    state: absent
  when: custom_wireguard_service_stat.stat.exists|bool
