---
# Project source code URL: https://gitlab.com/etke.cc/miounne

custom_miounne_enabled: false
custom_miounne_version: v2.2.1
matrix_server_fqn_miounne: "miounne.{{ matrix_domain }}"
matrix_nginx_proxy_proxy_miounne_hostname: "{{ matrix_server_fqn_miounne }}"
custom_miounne_docker_image: "registry.gitlab.com/etke.cc/miounne:{{ custom_miounne_version }}"
custom_miounne_docker_image_force_pull: "{{ custom_miounne_docker_image.endswith(':latest') }}"

custom_miounne_frequency: 10
custom_miounne_server_port: 8080

custom_miounne_spam_emails: []
custom_miounne_spam_hosts: []

custom_miounne_bmc_token: ""
custom_miounne_bmc_room: ""
custom_miounne_bmc_notify_extras: 0
custom_miounne_bmc_notify_members: 0
custom_miounne_bmc_notify_supporters: 0

custom_miounne_matrix_homeserver: "{{ matrix_homeserver_container_url }}"

custom_miounne_matrix_user_login: "miounne"
custom_miounne_matrix_user_password: ""
custom_miounne_matrix_user_displayname: "Mother Miounne"

custom_miounne_matrix_registration_url: ""
custom_miounne_matrix_registration_room: ""
custom_miounne_matrix_registration_secret: ""
custom_miounne_matrix_registration_notify_new: 0
custom_miounne_matrix_registration_notify_use: 0

# format:
  # - name: myform
  #   url: https://your-matrix-webhook.url/
  #   room: !dsadDSDad:yourdomain.com
  #   img: https://url-of-your-avatar.img
  #   fields: ["your", "form", "fields"]
  #   redirect: https://url-to-redirect-after-form.com
  #   ratelimit: 1r/m
  #   honeypot: honeypot_field_name
  #   extensions: []
custom_miounne_forms: []

#
# A list of extra arguments to pass to the container
custom_miounne_container_extra_arguments: []

# List of systemd services that miounne.service depends on
custom_miounne_systemd_required_services_list: ['docker.service']

custom_miounne_base_path: "{{ matrix_base_data_path }}/miounne"
custom_miounne_data_path: "{{ custom_miounne_base_path }}/data"
