---
custom_miounne_enabled: false
custom_miounne_version: latest
matrix_nginx_proxy_proxy_miounne_hostname: "{{ matrix_server_fqn_miounne }}"
custom_miounne_docker_image: "registry.gitlab.com/etke.cc/miounne:{{ custom_miounne_version }}"
custom_miounne_docker_image_force_pull: "{{ custom_miounne_docker_image.endswith(':latest') }}"

custom_miounne_server_port: 8080
custom_miounne_spam_emails: []
custom_miounne_spam_hosts: []

custom_miounne_matrix_homeserver: "{{ matrix_homeserver_container_url }}"

custom_miounne_matrix_user_login: "mother.miounne"
custom_miounne_matrix_user_password: ""
custom_miounne_matrix_user_displayname: "Mother Miounne"

custom_miounne_matrix_registration_url: ""
custom_miounne_matrix_registration_room: ""
custom_miounne_matrix_registration_secret: ""

# format:
  # - name: myform
  #   url: https://your-matrix-webhook.url/
  #   room: !dsadDSDad:yourdomain.com
  #   img: https://url-of-your-avatar.img
  #   fields: ["your", "form", "fields"]
  #   redirect: https://url-to-redirect-after-form.com
  #   honeypot: honeypot_field_name
custom_miounne_forms: []

#
# A list of extra arguments to pass to the container
custom_miounne_container_extra_arguments: []

# List of systemd services that miounne.service depends on
custom_miounne_systemd_required_services_list: ['docker.service']

custom_miounne_base_path: "{{ matrix_base_data_path }}/miounne"
custom_miounne_data_path: "{{ custom_miounne_base_path }}/data"

# Database-related configuration fields.
#
# To use SQLite:
# - change the engine (`custom_miounne_database_engine: 'sqlite'`)
# - plan your migration to Postgres, as this bridge does not support SQLite anymore (and neither will the playbook in the future).
#
# To use Postgres:
# - adjust your database credentials via the `custom_miounne_postgres_*` variables
custom_miounne_database_engine: 'postgres'

custom_miounne_sqlite_database_path_local: "{{ custom_miounne_data_path }}/miounne.db"
custom_miounne_sqlite_database_path_in_container: "/data/miounne.db"

custom_miounne_database_username: 'custom_miounne'
custom_miounne_database_password: 'some-password'
custom_miounne_database_hostname: 'matrix-postgres'
custom_miounne_database_port: 5432
custom_miounne_database_name: 'custom_miounne'

custom_miounne_database_connection_string: 'postgres://{{ custom_miounne_database_username }}:{{ custom_miounne_database_password }}@{{ custom_miounne_database_hostname }}:{{ custom_miounne_database_port }}/{{ custom_miounne_database_name }}?sslmode=disable'

custom_miounne_appservice_database: "{{
	{
		'sqlite': custom_miounne_sqlite_database_path_in_container,
		'postgres': custom_miounne_database_connection_string,
	}[custom_miounne_database_engine]
}}"
