---
custom_miounne_enabled: false
custom_miounne_version: latest
matrix_nginx_proxy_proxy_miounne_hostname: "{{ matrix_server_fqn_miounne }}"
custom_miounne_docker_image: "registry.gitlab.com/etke.cc/miounne:{{ custom_miounne_version }}"
custom_miounne_docker_image_force_pull: "{{ custom_miounne_docker_image.endswith(':latest') }}"

custom_miounne_server_port: 8080
custom_miounne_server_trustedproxies:
  - 172.18.0.0/16
custom_miounne_sentry: ""
custom_miounne_spam_emails: []
custom_miounne_spam_hosts: []

custom_miounne_matrix_homeserver: "{{ matrix_domain }}"
custom_miounne_matrix_user_login: "mother.miounne"
custom_miounne_matrix_user_password: ""
custom_miounne_matrix_user_displayname: "Mother Miounne"

# format:
  # - name: myform
  #   url: https://your-matrix-webhook.url/
  #   roomid: !dsadDSDad:yourdomain.com
  #   img: https://url-of-your-avatar.img
  #   fields: ["your", "form", "fields"]
  #   redirect: https://url-to-redirect-after-form.com
  #   honeypot: honeypot_field_name
custom_miounne_forms: []

#
# A list of extra arguments to pass to the container
custom_miounne_container_extra_arguments: []

# List of systemd services that miounne.service depends on
custom_miounne_systemd_required_services_list: ['docker.service']
