---
custom_languagetool_enabled: false
custom_languagetool_version: latest
matrix_nginx_proxy_proxy_languagetool_hostname: "{{ matrix_server_fqn_languagetool }}"
custom_languagetool_docker_image: "erikvl87/languagetool:{{ custom_languagetool_version }}"
custom_languagetool_docker_image_force_pull: "{{ custom_languagetool_docker_image.endswith(':latest') }}"

custom_languagetool_java_heap_min: 256m
custom_languagetool_java_heap_max: 512m
#
# A list of extra arguments to pass to the container
custom_languagetool_container_extra_arguments: []

# List of systemd services that languagetool.service depends on
custom_languagetool_systemd_required_services_list: ['docker.service']
