# SPDX-FileCopyrightText: 2022 MDAD project contributors
# SPDX-FileCopyrightText: 2024 wjbeckett
# SPDX-FileCopyrightText: 2024 - 2025 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure LiveKit Server paths exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: 0750
    owner: "{{ livekit_server_uid }}"
    group: "{{ livekit_server_gid }}"
  with_items:
    - {path: "{{ livekit_server_base_path }}", when: true}
    - {path: "{{ livekit_server_config_path }}", when: true}
    - {path: "{{ livekit_server_container_src_files_path }}", when: "{{ livekit_server_container_image_self_build }}"}
  when: "item.when | bool"

- name: Ensure LiveKit Server configuration installed
  ansible.builtin.copy:
    content: "{{ livekit_server_configuration | to_nice_yaml(indent=2, width=999999) }}"
    dest: "{{ livekit_server_config_path }}/config.yaml"
    mode: 0640
    owner: "{{ livekit_server_uid }}"
    group: "{{ livekit_server_gid }}"

- name: Ensure LiveKit Server labels file installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/labels.j2"
    dest: "{{ livekit_server_base_path }}/labels"
    mode: 0640
    owner: "{{ livekit_server_uid }}"
    group: "{{ livekit_server_gid }}"

- name: Ensure LiveKit Server container image is pulled
  community.docker.docker_image:
    name: "{{ livekit_server_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ livekit_server_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else livekit_server_container_image_force_pull }}"
  when: "not livekit_server_container_image_self_build | bool"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- when: "livekit_server_container_image_self_build | bool"
  block:
    - name: Ensure LiveKit Server repository is present on self-build
      ansible.builtin.git:
        repo: "{{ livekit_server_container_repo }}"
        version: "{{ livekit_server_container_repo_version }}"
        dest: "{{ livekit_server_container_src_files_path }}"
        force: "yes"
      become: true
      become_user: "{{ livekit_server_uid }}"
      register: livekit_server_git_pull_results

    - name: Ensure LiveKit Server container image is built
      community.docker.docker_image:
        name: "{{ livekit_server_container_image }}"
        source: build
        force_source: "{{ livekit_server_git_pull_results.changed if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
        force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else livekit_server_git_pull_results.changed }}"
        build:
          dockerfile: Dockerfile
          path: "{{ livekit_server_container_src_files_path }}"
          pull: true

- name: Ensure LiveKit Server container network is created
  community.general.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ livekit_server_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure LiveKit Server systemd service is installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/livekit-server.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ livekit_server_identifier }}.service"
    mode: 0644
