# SPDX-FileCopyrightText: 2022 MDAD project contributors
# SPDX-FileCopyrightText: 2024 wjbeckett
# SPDX-FileCopyrightText: 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of LiveKit Server service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ livekit_server_identifier }}.service"
  register: livekit_server_service_stat

- when: livekit_server_service_stat.stat.exists | bool
  block:
    - name: Ensure LiveKit Server is stopped
      ansible.builtin.service:
        name: "{{ livekit_server_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure LiveKit Server systemd service doesn't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ livekit_server_identifier }}.service"
        state: absent

    - name: Ensure LiveKit Server paths don't exist
      ansible.builtin.file:
        path: "{{ livekit_server_base_path }}"
        state: absent
