---
# Enable ufw installation and config
system_security_ufw_enabled: true

# integration with ssh
system_security_ssh_port: 22
# true - allow unrestricted SSH access by default, false - deny unrestricted SSH access by default
# You can add your own rules to allow SSH access from specific IPs or networks, keeping this var set to false
system_security_ufw_ssh_allowed: true

# Default (base) UFW rules (for matrix) - you definitely do NOT want to change this
system_security_ufw_rules_base:
  - name: HTTP
    rule: allow
    port: '80'
    proto: tcp
  - name: HTTPS
    rule: allow
    port: '443'
    proto: tcp
  - name: HTTPS over UDP
    rule: allow
    port: '443'
    proto: udp

# UFW rules to create in addition to the base (system_security_ufw_rules_base) and playbook- or group-defined rules
# You want to use this var to define your own rules
system_security_ufw_rules_custom: []

# this var is for playbook- or group-defined rules, you definitely do NOT want to change this in your vars.yml
system_security_ufw_rules_auto: []

# this var is the final (cumulative) list of UFW rules to apply. Use system_security_ufw_rules_custom to add your own rules.
system_security_ufw_rules: "{{ system_security_ufw_rules_base + system_security_ufw_rules_auto + system_security_ufw_rules_custom }}"
