---
- name: Check existence of custom-miounne.service
  stat:
    path: "{{ matrix_systemd_path }}/custom-miounne.service"
  register: custom_miounne_service_stat

- name: Ensure custom-miounne is stopped
  service:
    name: custom-miounne
    state: stopped
    enabled: no
    daemon_reload: yes
  register: stopping_result
  when: custom_miounne_service_stat.stat.exists|bool

- name: Ensure custom-miounne.service does not exists
  file:
    path: "{{ matrix_systemd_path }}/custom-miounne.service"
    state: absent
  when: custom_miounne_service_stat.stat.exists|bool

- name: Ensure systemd reloaded after custom-miounne.service removal
  service:
    daemon_reload: yes
  when: custom_miounne_service_stat.stat.exists|bool

- name: Ensure custom-miounne paths don't exist
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ custom_miounne_base_path }}"
    - "{{ custom_miounne_data_path }}"

- name: Ensure Matrix nginx-proxy configuration for miounne domain does not exists
  file:
    path: "{{ matrix_nginx_proxy_confd_path }}/matrix-custom-miounne.conf"
    state: absent

- name: Ensure custom-miounne docker image doesn't exist
  docker_image:
    name: "{{ custom_miounne_docker_image }}"
    state: absent
