---
- import_tasks: init.yml
  tags:
    - always

- import_tasks: install.yml
  when: custom_dnsmasq_enabled|bool
  tags:
    - setup-all
    - setup-dnsmasq

- import_tasks: uninstall.yml
  when: not custom_dnsmasq_enabled|bool
  tags:
    - setup-all
    - setup-dnsmasq
