---

- ansible.builtin.import_tasks: install.yml
  when: custom_dnsmasq_enabled|bool
  tags:
    - setup-all
    - setup-dnsmasq

- ansible.builtin.import_tasks: uninstall.yml
  when: not custom_dnsmasq_enabled|bool
  tags:
    - setup-all
    - setup-dnsmasq
