---
- set_fact:
    custom_softserve_requires_restart: false

- name: Ensure soft-serve paths exist
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0750
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
  with_items:
    - {path: "{{ custom_softserve_config_path }}", when: true}
    - {path: "{{ custom_softserve_data_path }}", when: true}
    - {path: "{{ custom_softserve_docker_src_files_path }}", when: true}
  when: "item.when|bool"

- name: Ensure soft-serve environment variables file created
  template:
    src: "{{ role_path }}/templates/env.j2"
    dest: "{{ custom_softserve_config_path }}/env"
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
    mode: 0640

- name: Ensure soft-serve image is pulled
  docker_image:
    name: "{{ custom_softserve_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ custom_softserve_docker_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else custom_softserve_docker_image_force_pull }}"
  when: "not custom_softserve_container_image_self_build|bool"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure soft-serve repository is present on self-build
  git:
    repo: "{{ custom_softserve_docker_repo }}"
    dest: "{{ custom_softserve_docker_src_files_path }}"
    force: "yes"
  become: true
  become_user: "{{ matrix_user_username }}"
  register: custom_softserve_git_pull_results
  when: "custom_softserve_container_image_self_build|bool"

- name: Ensure soft-serve image is built
  docker_image:
    name: "{{ custom_softserve_docker_image }}"
    source: build
    force_source: "{{ custom_softserve_git_pull_results.changed if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else matrix_mailer_git_pull_results.changed }}"
    build:
      dockerfile: Dockerfile
      path: "{{ custom_softserve_docker_src_files_path }}"
      pull: true
  when: "custom_softserve_container_image_self_build|bool"

- name: Ensure custom-softserve.service installed
  template:
    src: "{{ role_path }}/templates/systemd/custom-softserve.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/custom-softserve.service"
    mode: 0644
  register: custom_softserve_systemd_service_result

- name: Ensure systemd reloaded after custom-softserve.service installation
  service:
    daemon_reload: true
  when: "custom_softserve_systemd_service_result.changed|bool"

- name: Ensure custom-softserve.service restarted, if necessary
  service:
    name: "custom-softserve.service"
    state: restarted
  when: "custom_softserve_requires_restart|bool"
