---
moncfg_export_state: "/tmp/moncfg"
moncfg_export_file: "{{ inventory_dir }}/monitoring" # .node.yml and .html.yml will be added automatically
moncfg_export_group: customers
moncfg_export_node: []
moncfg_export_http: []

moncfg_labels:
  admin: "{{ matrix_monitoring_mxid | default(matrix_admin | default('')) }}"
  email: "{{ matrix_monitoring_email | default(matrix_ssl_lets_encrypt_support_email | default('')) }}"
  domain: "{{ matrix_domain }}"

moncfg_job_node_name: "node"
moncfg_job_node_targets:
  - "{{ matrix_server_fqn_matrix | default('matrix.' + matrix_domain) }}"
moncfg_job_node_auth_user: "{{ matrix_nginx_proxy_proxy_matrix_metrics_basic_auth_username | default ('') }}"
moncfg_job_node_auth_pass: "{{ matrix_nginx_proxy_proxy_matrix_metrics_basic_auth_password | default ('') }}"

moncfg_job_http_name: "http"
moncfg_job_http_targets: |
  {{
    (['https://' + (matrix_server_fqn_matrix | default('matrix.' + matrix_domain)) + '/_matrix/client/versions'] if matrix_synapse_enabled | default(True) else [])
    +
    (['https://' + (matrix_server_fqn_matrix | default('matrix.' + matrix_domain)) + ':8448/_matrix/federation/v1/version'] if (matrix_synapse_enabled | default(True) and matrix_synapse_federation_enabled | default(True)) else [])
    +
    (['https://' + matrix_domain + '/.well-known/matrix/server'] if (matrix_synapse_enabled | default(True) and matrix_synapse_federation_enabled | default(True)) else [])
    +
    (['https://' + matrix_server_fqn_buscarron | default('') + '/_health'] if matrix_bot_buscarron_enabled | default(False) else [])
    +
    (['https://' + matrix_server_fqn_cinny | default('')] if matrix_client_cinny_enabled | default(True) else [])
    +
    (['https://' + matrix_server_fqn_dimension | default('')] if matrix_dimension_enabled | default(False) else [])
    +
    (['https://' + matrix_server_fqn_element | default('')] if matrix_client_element_enabled | default(True) else [])
    +
    (['https://' + matrix_server_fqn_etherpad | default('') + etherpad_path_prefix | default('')] if etherpad_enabled | default(False) else [])
    +
    (['https://' + matrix_server_fqn_grafana | default('')] if grafana_enabled | default(False) else [])
    +
    (['https://' + matrix_server_fqn_hydrogen | default('')] if matrix_client_hydrogen_enabled | default(True) else [])
    +
    (['https://' + languagetool_hostname | default('') + languagetool_path_prefix | default('') + 'v2/languages'] if languagetool_enabled | default(False) else [])
    +
    (['https://' + miniflux_hostname | default('') + miniflux_path_prefix | default('')] if miniflux_enabled | default(False) else [])
    +
    (['https://' + matrix_server_fqn_ntfy | default('') + ntfy_path_prefix | default('')] if ntfy_enabled | default(False) else [])
    +
    (['https://' + radicale_hostname | default('') + radicale_path_prefix | default('/') + '.web/'] if radicale_enabled | default(False) else [])
    +
    (['https://' + matrix_server_fqn_sygnal | default('') + '/health'] if matrix_sygnal_enabled | default(False) else [])
    +
    (['https://' + uptime_kuma_hostname | default('') + uptime_kuma_path_prefix | default('')] if uptime_kuma_enabled | default(False) else [])
  }}
