- name: Clone git repo
  git:
    force: yes
    repo: "{{ integration_git2bunny_repo }}"
    dest: "{{ integration_git2bunny_tmp }}/git2bunny_{{ inventory_hostname }}"
    version: "{{ integration_git2bunny_repo_ref }}"
  delegate_to: 127.0.0.1
  become: no
  when: integration_git2bunny_enabled|bool
  tags:
    - setup-all
    - setup-git2bunny

- name: Build
  command: "{{ integration_git2bunny_command }}"
  args:
    chdir: "{{ integration_git2bunny_tmp }}/git2bunny_{{ inventory_hostname }}"
  delegate_to: 127.0.0.1
  become: no
  when: integration_git2bunny_enabled|bool and integration_git2bunny_command != ""
  tags:
    - setup-all
    - setup-git2bunny

- name: Cleanup build directory before deploy
  file:
    state: absent
    path: "{{ integration_git2bunny_tmp }}/git2bunny_{{ inventory_hostname }}/{{ integration_git2bunny_dist }}/{{ item }}"
  with_items: "{{ integration_git2bunny_exclude }}"
  delegate_to: 127.0.0.1
  become: no
  when: integration_git2bunny_enabled|bool
  tags:
    - setup-all
    - setup-website

- name: Get files list
  find:
    path: "{{ integration_git2bunny_tmp }}/git2bunny_{{ inventory_hostname }}/{{ integration_git2bunny_dist }}/"
    file_type: any
    recurse: yes
  register: files
  delegate_to: 127.0.0.1
  become: no
  when: integration_git2bunny_enabled|bool
  tags:
    - setup-all
    - setup-git2bunny

- name: Upload
  uri:
    url: "https://{{ integration_git2bunny_host }}/{{ integration_git2bunny_zone }}/{{ item.path|replace(integration_git2bunny_tmp + '/git2bunny_' + inventory_hostname + '/' + integration_git2bunny_dist, '')}}"
    method: PUT
    src: "{{ item.path }}"
    status_code: [200, 201]
    headers:
      AccessKey: "{{ integration_git2bunny_accesskey }}"
  loop: "{{ files.files }}"
  delegate_to: 127.0.0.1
  become: no
  when: integration_git2bunny_enabled|bool and item.isdir|bool == false
  tags:
    - setup-all
    - setup-git2bunny

- name: Remove temporary dir
  file:
    state: absent
    path: "{{ integration_git2bunny_tmp }}/git2bunny_{{ inventory_hostname }}"
  delegate_to: 127.0.0.1
  become: no
  when: integration_git2bunny_enabled|bool
  tags:
    - setup-all
    - setup-git2bunny
