# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Etherpad systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ etherpad_identifier }}.service"
  register: etherpad_service_stat

- name: Uninstall Etherpad systemd services and files
  when: etherpad_service_stat.stat.exists | bool
  block:
    - name: Ensure Etherpad systemd service is stopped
      ansible.builtin.service:
        name: "{{ etherpad_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Etherpad systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ etherpad_identifier }}.service"
        state: absent

    - name: Ensure Etherpad container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ etherpad_container_network }}"
        state: absent

    - name: Ensure Etherpad container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ etherpad_container_network }}
      register: network_deletion_result
      changed_when: etherpad_container_network in network_deletion_result.stdout

    - name: Ensure Etherpad path does not exist
      ansible.builtin.file:
        path: "{{ etherpad_base_path }}"
        state: absent
