---
- name: Restart Synapse
  service:
    enabled: yes
    state: restarted
    name: matrix-synapse
  when: matrix_synapse_enabled|bool
  tags:
    - setup-all
    - setup-synapse

- name: Restart Database (postgres)
  service:
    enabled: yes
    state: restarted
    name: matrix-postgres
  when: matrix_postgres_enabled|bool
  tags:
    - setup-all
    - setup-postgres

- name: Restart Discord bridge (appservice)
  service:
    enabled: yes
    state: restarted
    name: matrix-appservice-discord
  when: matrix_appservice_discord_enabled|bool
  tags:
    - setup-all
    - setup-appservice-discord

- name: Restart IRC bridge (appservice)
  service:
    enabled: yes
    state: restarted
    name: matrix-appservice-irc
  when: matrix_appservice_irc_enabled|bool
  tags:
    - setup-all
    - setup-appservice-irc

- name: Restart Slack bridge (appservice)
  service:
    enabled: yes
    state: restarted
    name: matrix-appservice-slack
  when: matrix_appservice_slack_enabled|bool
  tags:
    - setup-all
    - setup-appservice-slack

- name: Restart Webhooks bridge (appservice)
  service:
    enabled: yes
    state: restarted
    name: matrix-appservice-webhooks
  when: matrix_appservice_webhooks_enabled|bool
  tags:
    - setup-all
    - setup-appservice-webhooks

- name: Restart go-neb bot
  service:
    enabled: yes
    state: restarted
    name: matrix-bot-go-neb
  when: matrix_bot_go_neb_enabled|bool
  tags:
    - setup-all
    - setup-bot-go-neb

- name: Restart reminder bot
  service:
    enabled: yes
    state: restarted
    name: matrix-bot-matrix-reminder-bot
  when: matrix_bot_matrix_reminder_bot_enabled|bool
  tags:
    - setup-all
    - setup-bot-matrix-reminder-bot

- name: Restart mjolnir bot
  service:
    enabled: yes
    state: restarted
    name: matrix-bot-mjolnir
  when: matrix_bot_mjolnir_enabled|bool
  tags:
    - setup-all
    - setup-bot-mjolnir

- name: Restart Element
  service:
    enabled: yes
    state: restarted
    name: matrix-client-element
  when: matrix_client_element_enabled|bool
  tags:
    - setup-all
    - setup-client-element

- name: Restart Hydrogen
  service:
    enabled: yes
    state: restarted
    name: matrix-client-hydrogen
  when: matrix_client_hydrogen_enabled|bool
  tags:
    - setup-all
    - setup-client-hydrogen

- name: Restart Corporal
  service:
    enabled: yes
    state: restarted
    name: matrix-corporal
  when: matrix_corporal_enabled|bool
  tags:
    - setup-all
    - setup-corporal

- name: Restart Coturn
  service:
    enabled: yes
    state: restarted
    name: matrix-coturn
  when: matrix_coturn_enabled|bool
  tags:
    - setup-all
    - setup-coturn

- name: Restart Dimension
  service:
    enabled: yes
    state: restarted
    name: matrix-dimension
  when: matrix_dimension_enabled|bool
  tags:
    - setup-all
    - setup-dimension

- name: Restart Dynamic DNS
  service:
    enabled: yes
    state: restarted
    name: matrix-dynamic-dns
  when: matrix_dynamic_dns_enabled|bool
  tags:
    - setup-all
    - setup-dynamic-dns

- name: Restart Email2Matrix
  service:
    enabled: yes
    state: restarted
    name: matrix-email2matrix
  when: matrix_email2matrix_enabled|bool
  tags:
    - setup-all
    - setup-email2matrix

- name: Restart Etherpad
  service:
    enabled: yes
    state: restarted
    name: matrix-etherpad
  when: matrix_etherpad_enabled|bool
  tags:
    - setup-all
    - setup-etherpad

- name: Restart Grafana
  service:
    enabled: yes
    state: restarted
    name: matrix-grafana
  when: matrix_grafana_enabled|bool
  tags:
    - setup-all
    - setup-grafana

- name: Restart IRC bridge (heisenbridge)
  service:
    enabled: yes
    state: restarted
    name: matrix-heisenbridge
  when: matrix_heisenbridge_enabled|bool
  tags:
    - setup-all
    - setup-heisenbridge

- name: Restart Jitsi Conference Focus
  service:
    enabled: yes
    state: restarted
    name: matrix-jitsi-jicofo
  when: matrix_jitsi_enabled|bool
  tags:
    - setup-all
    - setup-jitsi

- name: Restart Jitsi Video Bridge
  service:
    enabled: yes
    state: restarted
    name: matrix-jitsi-jvb
  when: matrix_jitsi_enabled|bool
  tags:
    - setup-all
    - setup-jitsi

- name: Restart Jitsi Prosody
  service:
    enabled: yes
    state: restarted
    name: matrix-jitsi-prosody
  when: matrix_jitsi_enabled|bool
  tags:
    - setup-all
    - setup-jitsi

- name: Restart Jitsi Web
  service:
    enabled: yes
    state: restarted
    name: matrix-jitsi-web
  when: matrix_jitsi_enabled|bool
  tags:
    - setup-all
    - setup-jitsi

- name: Restart LanguageTool
  service:
    enabled: yes
    state: restarted
    name: custom-languagetool
  when: custom_languagetool_enabled|bool
  tags:
    - setup-all
    - setup-languagetool

- name: Restart Identity Server (ma1sd)
  service:
    enabled: yes
    state: restarted
    name: matrix-ma1sd
  when: matrix_ma1sd_enabled|bool
  tags:
    - setup-all
    - setup-ma1sd

- name: Restart Mailer (exim)
  service:
    enabled: yes
    state: restarted
    name: matrix-mailer
  when: matrix_mailer_enabled|bool
  tags:
    - setup-all
    - setup-mailer

- name: Restart matrix-registration
  service:
    enabled: yes
    state: restarted
    name: matrix-registration
  when: matrix_registration_enabled|bool
  tags:
    - setup-all
    - setup-registration

- name: Restart SMS bridge
  service:
    enabled: yes
    state: restarted
    name: matrix-sms-bridge
  when: matrix_sms_bridge_enabled|bool
  tags:
    - setup-all
    - setup-sms-bridge

- name: Restart Facebook bridge (mautrix)
  service:
    enabled: yes
    state: restarted
    name: matrix-mautrix-facebook
  when: matrix_mautrix_facebook_enabled|bool
  tags:
    - setup-all
    - setup-mautrix-facebook

- name: Restart Hangouts bridge (mautrix)
  service:
    enabled: yes
    state: restarted
    name: matrix-mautrix-hangouts
  when: matrix_mautrix_hangouts_enabled|bool
  tags:
    - setup-all
    - setup-mautrix-hangouts

- name: Restart Instagram bridge (mautrix)
  service:
    enabled: yes
    state: restarted
    name: matrix-mautrix-instagram
  when: matrix_mautrix_instagram_enabled|bool
  tags:
    - setup-all
    - setup-mautrix-instagram

- name: Restart Signal bridge (mautrix)
  service:
    enabled: yes
    state: restarted
    name: matrix-mautrix-signal
  when: matrix_mautrix_signal_enabled|bool
  tags:
    - setup-all
    - setup-mautrix-signal

- name: Restart Telegram bridge (mautrix)
  service:
    enabled: yes
    state: restarted
    name: matrix-mautrix-telegram
  when: matrix_mautrix_telegram_enabled|bool
  tags:
    - setup-all
    - setup-mautrix-telegram

- name: Restart WhatsApp bridge (mautrix)
  service:
    enabled: yes
    state: restarted
    name: matrix-mautrix-whatsapp
  when: matrix_mautrix_whatsapp_enabled|bool
  tags:
    - setup-all
    - setup-mautrix-whatsapp

- name: Restart Miniflux
  service:
    enabled: yes
    state: restarted
    name: custom-miniflux
  when: custom_miniflux_enabled|bool
  tags:
    - setup-all
    - setup-miniflux

- name: Restart Discord bridge (mx-puppet)
  service:
    enabled: yes
    state: restarted
    name: matrix-mx-puppet-discord
  when: matrix_mx_puppet_discord_enabled|bool
  tags:
    - setup-all
    - setup-mx-puppet-discord

- name: Restart GroupMe bridge (mx-puppet)
  service:
    enabled: yes
    state: restarted
    name: matrix-mx-puppet-groupme
  when: matrix_mx_puppet_groupme_enabled|bool
  tags:
    - setup-all
    - setup-mx-puppet-groupme

- name: Restart Instagram bridge (mx-puppet)
  service:
    enabled: yes
    state: restarted
    name: matrix-mx-puppet-instagram
  when: matrix_mx_puppet_instagram_enabled|bool
  tags:
    - setup-all
    - setup-mx-puppet-instagram

- name: Restart Skype bridge (mx-puppet)
  service:
    enabled: yes
    state: restarted
    name: matrix-mx-puppet-skype
  when: matrix_mx_puppet_skype_enabled|bool
  tags:
    - setup-all
    - setup-mx-puppet-skype

- name: Restart Slack bridge (mx-puppet)
  service:
    enabled: yes
    state: restarted
    name: matrix-mx-puppet-slack
  when: matrix_mx_puppet_slack_enabled|bool
  tags:
    - setup-all
    - setup-mx-puppet-slack

- name: Restart Steam bridge (mx-puppet)
  service:
    enabled: yes
    state: restarted
    name: matrix-mx-puppet-steam
  when: matrix_mx_puppet_steam_enabled|bool
  tags:
    - setup-all
    - setup-mx-puppet-steam

- name: Restart Twitter bridge (mx-puppet)
  service:
    enabled: yes
    state: restarted
    name: matrix-mx-puppet-twitter
  when: matrix_mx_puppet_twitter_enabled|bool
  tags:
    - setup-all
    - setup-mx-puppet-twitter

- name: Restart Proxy (nginx)
  service:
    enabled: yes
    state: restarted
    name: matrix-nginx-proxy
  when: matrix_nginx_proxy_enabled|bool
  tags:
    - setup-all
    - setup-ssl
    - setup-nginx-proxy

- name: Restart Prometheus
  service:
    enabled: yes
    state: restarted
    name: matrix-prometheus
  when: matrix_prometheus_enabled|bool
  tags:
    - setup-all
    - setup-prometheus

- name: Restart Prometheus Node Exporter
  service:
    enabled: yes
    state: restarted
    name: matrix-prometheus-node-exporter
  when: matrix_prometheus_node_exporter_enabled|bool
  tags:
    - setup-all
    - setup-prometheus
    - setup-prometheus-node-exporter

- name: Restart Prometheus Postgres Exporter
  service:
    enabled: yes
    state: restarted
    name: matrix-prometheus-postgres-exporter
  when: matrix_prometheus_postgres_exporter_enabled|bool
  tags:
    - setup-all
    - setup-prometheus
    - setup-prometheus-postgres-exporter

- name: Restart Redis
  service:
    enabled: yes
    state: restarted
    name: matrix-redis
  when: matrix_redis_enabled|bool
  tags:
    - setup-all
    - setup-redis

- name: Restart Sygnal
  service:
    enabled: yes
    state: restarted
    name: matrix-sygnal
  when: matrix_sygnal_enabled|bool
  tags:
    - setup-all
    - setup-sygnal

- name: Restart Synapse Admin
  service:
    enabled: yes
    state: restarted
    name: matrix-synapse-admin
  when: matrix_synapse_admin_enabled|bool
  tags:
    - setup-all
    - setup-synapse-admin

- name: Restart Miounne
  service:
    enabled: yes
    state: restarted
    name: custom-miounne
  when: custom_miounne_enabled|bool
  tags:
    - setup-all
    - setup-miounne
