---
# NOTE: "ignore_errors: yes" used as workaround for bad behavior on low RAM servers

- name: Reload init system before any restart
  service:
    daemon_reload: yes
  tags:
    - setup-all
    - restart-all
    - setup-appservice-discord
    - setup-appservice-irc
    - setup-appservice-slack
    - setup-appservice-webhooks
    - setup-backup-borg
    - setup-beeper-linkedin
    - setup-bot-go-neb
    - setup-bot-honoroit
    - setup-bot-matrix-reminder-bot
    - setup-bot-mjolnir
    - setup-client-cinny
    - setup-client-element
    - setup-client-hydrogen
    - setup-corporal
    - setup-coturn
    - setup-dendrite
    - setup-dimension
    - setup-dnsmasq
    - setup-dynamic-dns
    - setup-email2matrix
    - setup-etherpad
    - setup-grafana
    - setup-heisenbridge
    - setup-hookshot
    - setup-jitsi
    - setup-kuma
    - setup-languagetool
    - setup-ma1sd
    - setup-mailer
    - setup-matrix-registration
    - setup-mautrix-facebook
    - setup-mautrix-googlechat
    - setup-mautrix-hangouts
    - setup-mautrix-instagram
    - setup-mautrix-signal
    - setup-mautrix-telegram
    - setup-mautrix-twitter
    - setup-mautrix-whatsapp
    - setup-miniflux
    - setup-miounne
    - setup-mx-puppet-discord
    - setup-mx-puppet-groupme
    - setup-mx-puppet-instagram
    - setup-mx-puppet-skype
    - setup-mx-puppet-slack
    - setup-mx-puppet-steam
    - setup-mx-puppet-twitter
    - setup-nginx-proxy
    - setup-postgres
    - setup-postgres-backup
    - setup-prometheus
    - setup-prometheus-node-exporter
    - setup-prometheus-postgres-exporter
    - setup-radicale
    - setup-redis
    - setup-sms-bridge
    - setup-ssl
    - setup-sygnal
    - setup-synapse
    - setup-synapse-admin

- name: Restart Synapse
  service:
    enabled: yes
    state: restarted
    name: matrix-synapse
  when: matrix_synapse_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-synapse

- name: Restart Dendrite
  service:
    enabled: yes
    state: restarted
    name: matrix-dendrite
  when: matrix_dendrite_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-dendrite

- name: Restart Database (postgres)
  service:
    enabled: yes
    state: restarted
    name: matrix-postgres
  when: matrix_postgres_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-postgres

- name: Restart Database Backup (postgres-backup)
  service:
    enabled: yes
    state: restarted
    name: matrix-postgres-backup
  when: matrix_postgres_backup_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-postgres-backup

- name: Restart Discord bridge (appservice)
  service:
    enabled: yes
    state: restarted
    name: matrix-appservice-discord
  when: matrix_appservice_discord_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-appservice-discord

- name: Restart IRC bridge (appservice)
  service:
    enabled: yes
    state: restarted
    name: matrix-appservice-irc
  when: matrix_appservice_irc_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-appservice-irc

- name: Restart Slack bridge (appservice)
  service:
    enabled: yes
    state: restarted
    name: matrix-appservice-slack
  when: matrix_appservice_slack_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-appservice-slack

- name: Restart Webhooks bridge (appservice)
  service:
    enabled: yes
    state: restarted
    name: matrix-appservice-webhooks
  when: matrix_appservice_webhooks_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-appservice-webhooks

- name: Restart borg backup timer
  service:
    enabled: yes
    state: restarted
    name: matrix-backup-borg.timer
  when: matrix_backup_borg_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-backup-borg

- name: Restart linkedin bridge (beeper)
  service:
    enabled: yes
    state: restarted
    name: matrix-beeper-linkedin
  when: matrix_beeper_linkedin_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-beeper-linkedin

- name: Restart go-neb bot
  service:
    enabled: yes
    state: restarted
    name: matrix-bot-go-neb
  when: matrix_bot_go_neb_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-bot-go-neb

- name: Restart Honoroit
  service:
    enabled: yes
    state: restarted
    name: matrix-bot-honoroit
  when: matrix_bot_honoroit_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-bot-honoroit

- name: Restart reminder bot
  service:
    enabled: yes
    state: restarted
    name: matrix-bot-matrix-reminder-bot
  when: matrix_bot_matrix_reminder_bot_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-bot-matrix-reminder-bot

- name: Restart mjolnir bot
  service:
    enabled: yes
    state: restarted
    name: matrix-bot-mjolnir
  when: matrix_bot_mjolnir_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-bot-mjolnir

- name: Restart Cinny
  service:
    enabled: yes
    state: restarted
    name: matrix-client-cinny
  when: matrix_client_cinny_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-client-cinny

- name: Restart Element
  service:
    enabled: yes
    state: restarted
    name: matrix-client-element
  when: matrix_client_element_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-client-element

- name: Restart Hydrogen
  service:
    enabled: yes
    state: restarted
    name: matrix-client-hydrogen
  when: matrix_client_hydrogen_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-client-hydrogen

- name: Restart Corporal
  service:
    enabled: yes
    state: restarted
    name: matrix-corporal
  when: matrix_corporal_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-corporal

- name: Restart Coturn (reload timer)
  service:
    enabled: yes
    state: restarted
    name: matrix-coturn-reload.timer
  when: matrix_coturn_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-coturn

- name: Restart Coturn
  service:
    enabled: yes
    state: restarted
    name: matrix-coturn
  when: matrix_coturn_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-coturn

- name: Restart Dimension
  service:
    enabled: yes
    state: restarted
    name: matrix-dimension
  when: matrix_dimension_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-dimension

- name: Restart dnsmasq
  service:
    enabled: yes
    state: restarted
    name: custom-dnsmasq
  when: custom_dnsmasq_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-dnsmasq

- name: Restart Dynamic DNS
  service:
    enabled: yes
    state: restarted
    name: matrix-dynamic-dns
  when: matrix_dynamic_dns_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-dynamic-dns

- name: Restart Email2Matrix
  service:
    enabled: yes
    state: restarted
    name: matrix-email2matrix
  when: matrix_email2matrix_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-email2matrix

- name: Restart Etherpad
  service:
    enabled: yes
    state: restarted
    name: matrix-etherpad
  when: matrix_etherpad_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-etherpad

- name: Restart Grafana
  service:
    enabled: yes
    state: restarted
    name: matrix-grafana
  when: matrix_grafana_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-grafana

- name: Restart IRC bridge (heisenbridge)
  service:
    enabled: yes
    state: restarted
    name: matrix-heisenbridge
  when: matrix_heisenbridge_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-heisenbridge

- name: Restart Hookshot bridge
  service:
    enabled: yes
    state: restarted
    name: matrix-hookshot
  when: matrix_hookshot_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-hookshot

- name: Restart Jitsi Conference Focus
  service:
    enabled: yes
    state: restarted
    name: matrix-jitsi-jicofo
  when: matrix_jitsi_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-jitsi

- name: Restart Jitsi Video Bridge
  service:
    enabled: yes
    state: restarted
    name: matrix-jitsi-jvb
  when: matrix_jitsi_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-jitsi

- name: Restart Jitsi Prosody
  service:
    enabled: yes
    state: restarted
    name: matrix-jitsi-prosody
  when: matrix_jitsi_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-jitsi

- name: Restart Jitsi Web
  service:
    enabled: yes
    state: restarted
    name: matrix-jitsi-web
  when: matrix_jitsi_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-jitsi

- name: Restart Uptime Kuma
  service:
    enabled: yes
    state: restarted
    name: custom-kuma
  when: custom_kuma_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-kuma

- name: Restart LanguageTool
  service:
    enabled: yes
    state: restarted
    name: custom-languagetool
  when: custom_languagetool_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-languagetool

- name: Restart Identity Server (ma1sd)
  service:
    enabled: yes
    state: restarted
    name: matrix-ma1sd
  when: matrix_ma1sd_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-ma1sd

- name: Restart Mailer (exim)
  service:
    enabled: yes
    state: restarted
    name: matrix-mailer
  when: matrix_mailer_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-mailer

- name: Restart matrix-registration
  service:
    enabled: yes
    state: restarted
    name: matrix-registration
  when: matrix_registration_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-matrix-registration

- name: Restart SMS bridge
  service:
    enabled: yes
    state: restarted
    name: matrix-sms-bridge
  when: matrix_sms_bridge_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-sms-bridge

- name: Restart Facebook bridge (mautrix)
  service:
    enabled: yes
    state: restarted
    name: matrix-mautrix-facebook
  when: matrix_mautrix_facebook_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-mautrix-facebook

- name: Restart Google Chat bridge (mautrix)
  service:
    enabled: yes
    state: restarted
    name: matrix-mautrix-googlechat
  when: matrix_mautrix_googlechat_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-mautrix-googlechat

- name: Restart Hangouts bridge (mautrix)
  service:
    enabled: yes
    state: restarted
    name: matrix-mautrix-hangouts
  when: matrix_mautrix_hangouts_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-mautrix-hangouts

- name: Restart Instagram bridge (mautrix)
  service:
    enabled: yes
    state: restarted
    name: matrix-mautrix-instagram
  when: matrix_mautrix_instagram_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-mautrix-instagram

- name: Restart Signal bridge (mautrix)
  service:
    enabled: yes
    state: restarted
    name: matrix-mautrix-signal
  when: matrix_mautrix_signal_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-mautrix-signal

- name: Restart Signal bridge's daemon (mautrix)
  service:
    enabled: yes
    state: restarted
    name: matrix-mautrix-signal-daemon
  when: matrix_mautrix_signal_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-mautrix-signal

- name: Restart Telegram bridge (mautrix)
  service:
    enabled: yes
    state: restarted
    name: matrix-mautrix-telegram
  when: matrix_mautrix_telegram_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-mautrix-telegram

- name: Restart Twitter bridge (mautrix)
  service:
    enabled: yes
    state: restarted
    name: matrix-mautrix-twitter
  when: matrix_mautrix_twitter_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-mautrix-twitter

- name: Restart WhatsApp bridge (mautrix)
  service:
    enabled: yes
    state: restarted
    name: matrix-mautrix-whatsapp
  when: matrix_mautrix_whatsapp_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-mautrix-whatsapp

- name: Restart Miniflux
  service:
    enabled: yes
    state: restarted
    name: custom-miniflux
  when: custom_miniflux_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-miniflux

- name: Restart Discord bridge (mx-puppet)
  service:
    enabled: yes
    state: restarted
    name: matrix-mx-puppet-discord
  when: matrix_mx_puppet_discord_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-mx-puppet-discord

- name: Restart GroupMe bridge (mx-puppet)
  service:
    enabled: yes
    state: restarted
    name: matrix-mx-puppet-groupme
  when: matrix_mx_puppet_groupme_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-mx-puppet-groupme

- name: Restart Instagram bridge (mx-puppet)
  service:
    enabled: yes
    state: restarted
    name: matrix-mx-puppet-instagram
  when: matrix_mx_puppet_instagram_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-mx-puppet-instagram

- name: Restart Skype bridge (mx-puppet)
  service:
    enabled: yes
    state: restarted
    name: matrix-mx-puppet-skype
  when: matrix_mx_puppet_skype_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-mx-puppet-skype

- name: Restart Slack bridge (mx-puppet)
  service:
    enabled: yes
    state: restarted
    name: matrix-mx-puppet-slack
  when: matrix_mx_puppet_slack_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-mx-puppet-slack

- name: Restart Steam bridge (mx-puppet)
  service:
    enabled: yes
    state: restarted
    name: matrix-mx-puppet-steam
  when: matrix_mx_puppet_steam_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-mx-puppet-steam

- name: Restart Twitter bridge (mx-puppet)
  service:
    enabled: yes
    state: restarted
    name: matrix-mx-puppet-twitter
  when: matrix_mx_puppet_twitter_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-mx-puppet-twitter

- name: Restart ssl renewal service
  service:
    enabled: yes
    state: restarted
    name: matrix-ssl-lets-encrypt-certificates-renew.service
  when: matrix_nginx_proxy_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-ssl
    - setup-nginx-proxy

- name: Restart ssl renewal timer
  service:
    enabled: yes
    state: restarted
    name: matrix-ssl-lets-encrypt-certificates-renew.timer
  when: matrix_nginx_proxy_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-ssl
    - setup-nginx-proxy

- name: Restart nginx-proxy reload service
  service:
    enabled: yes
    state: restarted
    name: matrix-ssl-nginx-proxy-reload.timer
  when: matrix_nginx_proxy_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-ssl
    - setup-nginx-proxy

- name: Restart nginx-proxy reload timer
  service:
    enabled: yes
    state: restarted
    name: matrix-ssl-nginx-proxy-reload.timer
  when: matrix_nginx_proxy_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-ssl
    - setup-nginx-proxy

- name: Restart Proxy (nginx)
  service:
    enabled: yes
    state: restarted
    name: matrix-nginx-proxy
  when: matrix_nginx_proxy_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-ssl
    - setup-nginx-proxy

- name: Restart Prometheus
  service:
    enabled: yes
    state: restarted
    name: matrix-prometheus
  when: matrix_prometheus_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-prometheus

- name: Restart Prometheus Node Exporter
  service:
    enabled: yes
    state: restarted
    name: matrix-prometheus-node-exporter
  when: matrix_prometheus_node_exporter_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-prometheus
    - setup-prometheus-node-exporter

- name: Restart Prometheus Postgres Exporter
  service:
    enabled: yes
    state: restarted
    name: matrix-prometheus-postgres-exporter
  when: matrix_prometheus_postgres_exporter_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-prometheus
    - setup-prometheus-postgres-exporter

- name: Restart Radicale
  service:
    enabled: yes
    state: restarted
    name: custom-radicale
  when: custom_radicale_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-radicale

- name: Restart Redis
  service:
    enabled: yes
    state: restarted
    name: matrix-redis
  when: matrix_redis_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-redis

- name: Restart Sygnal
  service:
    enabled: yes
    state: restarted
    name: matrix-sygnal
  when: matrix_sygnal_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-sygnal

- name: Restart Synapse Admin
  service:
    enabled: yes
    state: restarted
    name: matrix-synapse-admin
  when: matrix_synapse_admin_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-synapse-admin

- name: Restart Miounne
  service:
    enabled: yes
    state: restarted
    name: custom-miounne
  when: custom_miounne_enabled|bool
  ignore_errors: yes
  tags:
    - setup-all
    - restart-all
    - setup-miounne
