---
- name: Update packages list
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Install fail2ban
  apt:
    name: fail2ban

- name: Ensure fail2ban stared and running
  systemd:
    state: started
    enabled: yes
    name: fail2ban
