# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Initial task for additional JVBs installation
  ansible.builtin.set_fact:
    devture_systemd_service_manager_services_list_auto: "{{ [{'name': (jitsi_identifier + '-jvb.service'), 'priority': 1000, 'groups': ['jitsi', 'jitsi-jvb']}] }}"
  when: jitsi_enabled | bool
