# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure jitsi-jvb paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
    owner: "{{ jitsi_uid }}"
    group: "{{ jitsi_gid }}"
  with_items:
    - "{{ jitsi_jvb_base_path }}"
    - "{{ jitsi_jvb_config_path }}"

- name: Ensure jitsi-jvb support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/jvb/{{ item }}.j2"
    dest: "{{ jitsi_jvb_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ jitsi_uid }}"
    group: "{{ jitsi_gid }}"
  with_items:
    - env
    - labels

- name: Ensure jitsi-jvb configuration files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/jvb/{{ item }}.j2"
    dest: "{{ jitsi_jvb_config_path }}/{{ item }}"
    mode: "0644"
    owner: "{{ jitsi_uid }}"
    group: "{{ jitsi_gid }}"
  with_items:
    - custom-sip-communicator.properties
    - logging.properties

- name: Ensure jitsi-jvb container image is pulled via community.docker.docker_image
  when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
  community.docker.docker_image:
    name: "{{ jitsi_jvb_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ jitsi_jvb_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else jitsi_jvb_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure jitsi-jvb container image is pulled via ansible.builtin.command
  when: devture_systemd_docker_base_container_image_pull_method == 'command'
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ jitsi_jvb_container_image }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed
  changed_when: "'Downloaded newer image' in result.stdout"

- name: Ensure jitsi-jvb systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/jvb/systemd/jvb.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ jitsi_identifier }}-jvb.service"
    mode: "0644"
