# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform tasks for additional JVBs installation
  when: jitsi_enabled | bool
  tags:
    - setup-additional-jitsi-jvb
    - install-additional-jitsi-jvb
  block:
    - name: Perform an initial task for additional JVBs installation
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/init_additional_jvb.yml"

- name: Perform Jitsi base installation tasks
  when: jitsi_enabled | bool
  tags:
    - setup-all
    - setup-jitsi
    - setup-additional-jitsi-jvb
    - install-all
    - install-jitsi
    - install-additional-jitsi-jvb
  block:
    - name: Validate Jitsi configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install base for Jitsi
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/base_install.yml"

- name: Perform Jitsi components installation tasks
  when: jitsi_enabled | bool
  tags:
    - setup-all
    - setup-jitsi
    - install-all
    - install-jitsi
  block:
    - name: Install jitsi-web
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/web_install.yml"
    - name: Install jitsi-prosody
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/prosody_install.yml"
    - name: Install jitsi-jicofo
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/jicofo_install.yml"

- name: Perform additional JVBs installation tasks
  when: jitsi_enabled | bool
  tags:
    - setup-all
    - setup-jitsi
    - setup-additional-jitsi-jvb
    - install-all
    - install-jitsi
    - install-additional-jitsi-jvb
  block:
    - name: Install jitsi-jvb
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/jvb_install.yml"

- name: Perform Jitsi components uninstallation tasks
  when: not jitsi_enabled | bool
  tags:
    - setup-all
    - setup-jitsi
  block:
    - name: Uninstall jitsi-web
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/web_uninstall.yml"
    - name: Uninstall jitsi-prosody
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/prosody_uninstall.yml"
    - name: Uninstall jitsi-jicofo
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/jicofo_uninstall.yml"

- name: Perform additional JVBs uninstallation tasks
  when: not jitsi_enabled | bool
  tags:
    - setup-all
    - setup-jitsi
    - setup-additional-jitsi-jvb
  block:
    - name: Uninstall jitsi-jvb
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/jvb_uninstall.yml"

# Remove jitsi_base_path in the end
- name: Perform Jitsi base uninstallation tasks
  when: not jitsi_enabled | bool
  tags:
    - setup-all
    - setup-jitsi
    - setup-additional-jitsi-jvb
  block:
    - name: Uninstall base for Jitsi
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/base_uninstall.yml"

- name: Perform Jitsi self-check tasks
  tags:
    - self-check
  block:
    - name: Perform self-check for authentication with Matrix OpenID
      when: jitsi_enable_auth | bool and jitsi_auth_type == 'matrix'
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/self_check_matrix_auth.yml"
