---
- name: "Set up a Matrix server"
  hosts: "{{ target if target is defined else 'etke_servers' }}"
  become: true
  vars:
    matrix_playbook_docker_installation_enabled: false
    matrix_playbook_migration_debian_signedby_migration_enabled: false

  roles:
    # MATRIX
    - galaxy/playbook_help
    - galaxy/systemd_docker_base
    - custom/matrix_playbook_migration
    - when: devture_docker_sdk_for_python_installation_enabled | bool
      role: galaxy/docker_sdk_for_python
      tags:
        - setup-docker
        - setup-all
        - install-docker
        - install-all
    - when: devture_timesync_installation_enabled | bool
      role: galaxy/timesync
      tags:
        - setup-timesync
        - setup-all
        - install-timesync
        - install-all
    - custom/matrix-base
    - galaxy/exim_relay
    - galaxy/container_socket_proxy
    - galaxy/traefik
    - galaxy/traefik_certs_dumper
    - galaxy/postgres
    - galaxy/keydb
    - galaxy/valkey
    - custom/matrix-appservice-double-puppet
    - custom/matrix-bridge-appservice-discord
    - custom/matrix-bridge-beeper-linkedin
    - custom/matrix-bridge-go-skype-bridge
    - custom/matrix-bridge-wechat
    - custom/matrix-bridge-mautrix-twitter
    - custom/matrix-bridge-mautrix-hangouts
    - custom/matrix-bridge-mautrix-googlechat
    - custom/matrix-bridge-mautrix-meta-messenger
    - custom/matrix-bridge-mautrix-meta-instagram
    - custom/matrix-bridge-mautrix-signal
    - custom/matrix-bridge-mautrix-telegram
    - custom/matrix-bridge-mautrix-gmessages
    - custom/matrix-bridge-mautrix-whatsapp
    - custom/matrix-bridge-mautrix-discord
    - custom/matrix-bridge-mautrix-slack
    - custom/matrix-bridge-postmoogle
    - custom/matrix-bridge-heisenbridge
    - custom/matrix-bridge-hookshot
    - custom/matrix-bot-matrix-reminder-bot
    - custom/matrix-bot-maubot
    - custom/matrix-bot-buscarron
    - custom/matrix-bot-baibot
    - custom/matrix-bot-honoroit
    - custom/matrix-bot-go-neb
    - custom/matrix-bot-chatgpt
    - custom/matrix-synapse
    - custom/matrix-synapse-auto-compressor
    - custom/matrix-synapse-reverse-proxy-companion
    - custom/matrix-synapse-admin
    - custom/matrix-synapse-usage-exporter
    - galaxy/prometheus_node_exporter
    - galaxy/prometheus_postgres_exporter
    - galaxy/prometheus
    - galaxy/grafana
    - custom/matrix-prometheus-services-connect
    - custom/matrix-registration
    - custom/matrix-client-element
    - custom/matrix-client-hydrogen
    - custom/matrix-client-cinny
    - custom/matrix-client-schildichat
    - galaxy/jitsi
    - custom/matrix-ma1sd
    - galaxy/etherpad
    - custom/matrix-sliding-sync
    - custom/matrix-sygnal
    - galaxy/ntfy
    # END MATRIX

    # CUSTOM
    - galaxy/swap
    - galaxy/ssh
    - galaxy/ufw
    - galaxy/fail2ban
    - galaxy/uptime_kuma
    - galaxy/languagetool
    - galaxy/linkding
    - galaxy/miniflux
    - galaxy/gotosocial
    - galaxy/radicale
    - galaxy/vaultwarden
    - galaxy/firezone
    - galaxy/funkwhale
    - galaxy/peertube
    # END CUSTOM

    # MATRIX
    - custom/matrix-static-files
    # END MATRIX

    # MATRIX
    - custom/matrix-coturn
    # - custom/matrix-media-repo # unused
    - galaxy/auxiliary
    - galaxy/postgres_backup
    - galaxy/backup_borg
    - when: devture_systemd_service_manager_enabled | bool
      role: galaxy/systemd_service_manager
    - custom/matrix-user-creator
    - custom/matrix-common-after
    - galaxy/playbook_state_preserver
    - galaxy/playbook_runtime_messages
    # END MATRIX

    # CUSTOM
    - custom/skopeo
    - custom/mrs-discovery
    - galaxy/cleanup
    # END CUSTOM
