---
- name: "Set up a Matrix server"
  hosts: "{{ target if target is defined else 'matrix_servers' }}"
  become: true

  # Temporary workaround, ref: https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/895
  vars_files:
    - "{{ playbook_dir }}/../upstream/roles/matrix-synapse/vars/workers.yml"

  roles:
    - system/init
    - matrix-base
    - matrix-dynamic-dns
    - matrix-mailer
    - matrix-postgres
    - matrix-redis
    - matrix-corporal
    - matrix-bridge-appservice-discord
    - matrix-bridge-appservice-slack
    - matrix-bridge-appservice-webhooks
    - matrix-bridge-appservice-irc
    - matrix-bridge-beeper-linkedin
    - matrix-bridge-mautrix-facebook
    - matrix-bridge-mautrix-twitter
    - matrix-bridge-mautrix-hangouts
    - matrix-bridge-mautrix-googlechat
    - matrix-bridge-mautrix-instagram
    - matrix-bridge-mautrix-signal
    - matrix-bridge-mautrix-telegram
    - matrix-bridge-mautrix-whatsapp
    - matrix-bridge-mx-puppet-discord
    - matrix-bridge-mx-puppet-groupme
    - matrix-bridge-mx-puppet-steam
    - matrix-bridge-mx-puppet-skype
    - matrix-bridge-mx-puppet-slack
    - matrix-bridge-mx-puppet-twitter
    - matrix-bridge-mx-puppet-instagram
    - matrix-bridge-sms
    - matrix-bridge-heisenbridge
    - matrix-bridge-hookshot
    - matrix-bot-matrix-reminder-bot
    - matrix-bot-honoroit
    - matrix-bot-go-neb
    - matrix-bot-mjolnir
    - matrix-synapse
    - matrix-dendrite
    - matrix-synapse-admin
    - matrix-prometheus-node-exporter
    - matrix-prometheus
    - matrix-grafana
    - matrix-registration
    - matrix-client-element
    - matrix-client-hydrogen
    - matrix-client-cinny
    - matrix-jitsi
    - matrix-ma1sd
    - matrix-dimension
    - matrix-etherpad
    - matrix-email2matrix
    - matrix-sygnal
    - matrix-nginx-proxy
    # CUSTOM
    - system/swap
    - system/security
    - custom/dnsmasq
    - custom/kuma
    - custom/languagetool
    - custom/miniflux
    - custom/miounne
    - custom/radicale
    - custom/wireguard
    - integration/uptimerobot
    - integration/git2bunny
    - matrix/nginx-proxy-website
    - matrix/nginx-proxy-health
    # END CUSTOM
    - matrix-coturn
    - matrix-aux
    - matrix-postgres-backup
    - matrix-prometheus-postgres-exporter
    - matrix-backup-borg
    - matrix-common-after
    # CUSTOM
    - matrix/restart
    - system/maintenance
    # END CUSTOM

