---
- name: "Set up a Matrix server"
  hosts: "{{ target if target is defined else 'etke_servers' }}"
  become: true
  vars:
    matrix_playbook_docker_installation_enabled: false

  roles:
    # MATRIX
    - galaxy/playbook_help
    - galaxy/systemd_docker_base
    - custom/matrix_playbook_migration
    - when: devture_docker_sdk_for_python_installation_enabled | bool
      role: galaxy/docker_sdk_for_python
      tags:
        - setup-docker
        - setup-all
        - install-docker
        - install-all
    - when: devture_timesync_installation_enabled | bool
      role: galaxy/timesync
      tags:
        - setup-timesync
        - setup-all
        - install-timesync
        - install-all
    - custom/matrix-base
    # - custom/matrix-dynamic-dns # unused
    - custom/matrix-mailer
    - galaxy/postgres
    - galaxy/redis
    # - custom/matrix-corporal # unused
    - custom/matrix-bridge-appservice-discord
    # - custom/matrix-bridge-appservice-slack # unused
    - custom/matrix-bridge-appservice-webhooks
    # - custom/matrix-bridge-appservice-irc # unused
    # - custom/matrix-bridge-appservice-kakaotalk # unused disabled due to issues
    - custom/matrix-bridge-beeper-linkedin
    - custom/matrix-bridge-go-skype-bridge
    - custom/matrix-bridge-mautrix-facebook
    - custom/matrix-bridge-mautrix-twitter
    - custom/matrix-bridge-mautrix-hangouts
    - custom/matrix-bridge-mautrix-googlechat
    - custom/matrix-bridge-mautrix-instagram
    - custom/matrix-bridge-mautrix-signal
    - custom/matrix-bridge-mautrix-telegram
    - custom/matrix-bridge-mautrix-gmessages
    - custom/matrix-bridge-mautrix-whatsapp
    - custom/matrix-bridge-mautrix-discord
    - custom/matrix-bridge-mautrix-slack
    - custom/matrix-bridge-mx-puppet-discord
    - custom/matrix-bridge-mx-puppet-groupme
    - custom/matrix-bridge-mx-puppet-steam
    - custom/matrix-bridge-mx-puppet-slack
    # - custom/matrix-bridge-mx-puppet-twitter # unused
    # - custom/matrix-bridge-mx-puppet-instagram # unused
    # - custom/matrix-bridge-sms # unused
    - custom/matrix-bridge-heisenbridge
    - custom/matrix-bridge-hookshot
    - custom/matrix-bot-matrix-reminder-bot
    # - custom/matrix-bot-matrix-registration-bot # unused
    # - custom/matrix-bot-maubot # unused
    - custom/matrix-bot-buscarron
    - custom/matrix-bot-honoroit
    - custom/matrix-bot-postmoogle
    - custom/matrix-bot-go-neb
    # - custom/matrix-bot-mjolnir # unused
    # - custom/matrix-bot-draupnir # unused
    - custom/matrix-bot-chatgpt
    # - custom/matrix-cactus-comments # unused
    # - custom/matrix-rageshake # unused
    - custom/matrix-synapse
    - custom/matrix-synapse-auto-compressor
    - custom/matrix-synapse-reverse-proxy-companion
    # - custom/matrix-dendrite # unused
    # - custom/matrix-conduit # unused
    - custom/matrix-synapse-admin
    - galaxy/prometheus_node_exporter
    - galaxy/prometheus_postgres_exporter
    - custom/matrix-prometheus-nginxlog-exporter
    - galaxy/prometheus
    - galaxy/grafana
    - custom/matrix-prometheus-services-connect
    - custom/matrix-prometheus-services-proxy-connect
    - custom/matrix-registration
    - custom/matrix-client-element
    - custom/matrix-client-hydrogen
    - custom/matrix-client-cinny
    - custom/matrix-client-schildichat
    - galaxy/jitsi
    - custom/matrix-user-verification-service
    # - custom/matrix-ldap-registration-proxy # unused
    - custom/matrix-ma1sd
    - custom/matrix-dimension
    - galaxy/etherpad
    - custom/etherpad-proxy-connect
    - custom/matrix-sliding-sync
    - custom/matrix-email2matrix
    - custom/matrix-sygnal
    - galaxy/ntfy
    # END MATRIX

    # CUSTOM
    - galaxy/swap
    - galaxy/ssh
    - galaxy/ufw
    - galaxy/fail2ban
    - custom/dnsmasq
    - galaxy/uptime_kuma
    - galaxy/languagetool
    - custom/nginx-migration
    - galaxy/linkding
    - galaxy/miniflux
    - galaxy/gotosocial
    - galaxy/radicale
    - galaxy/vaultwarden
    - custom/wireguard
    # END CUSTOM

    # MATRIX
    - custom/matrix-nginx-proxy
    # END MATRIX

    # CUSTOM
    - matrix/nginx-proxy-website
    # END CUSTOM

    # MATRIX
    - custom/matrix-coturn
    # - custom/matrix-media-repo # unused
    - galaxy/auxiliary
    - galaxy/postgres_backup
    - galaxy/backup_borg
    - custom/matrix-user-creator
    - custom/matrix-common-after
    - galaxy/container_socket_proxy
    - when: devture_traefik_enabled | bool
      role: galaxy/traefik
    - when: devture_traefik_certs_dumper_enabled | bool
      role: galaxy/traefik_certs_dumper
    - when: devture_systemd_service_manager_enabled | bool
      role: galaxy/systemd_service_manager
    - galaxy/playbook_state_preserver
    - galaxy/playbook_runtime_messages
    # END MATRIX

    # CUSTOM
    - custom/skopeo
    - custom/mrs-discovery
    - galaxy/cleanup
    # END CUSTOM
