---

- tags:
    - setup-all
    - setup-exim-relay
    - install-all
    - install-exim-relay
  block:
    - when: exim_relay_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: exim_relay_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- tags:
    - setup-all
    - setup-exim-relay
  block:
    - when: not exim_relay_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
