---
custom_honoroit_enabled: false
custom_honoroit_version: latest
custom_honoroit_docker_image: "registry.gitlab.com/etke.cc/honoroit:{{ custom_honoroit_version }}"
custom_honoroit_docker_image_force_pull: "{{ custom_honoroit_docker_image.endswith(':latest') }}"

custom_honoroit_homeserver: "{{ matrix_homeserver_container_url }}"

custom_honoroit_login: "honoroit"
custom_honoroit_password: ""
custom_honoroit_roomid: ""
custom_honoroit_loglevel: "INFO"
custom_honoroit_sentry: ""

# Database-related configuration fields.
#
# To use SQLite:
# - change the engine (`custom_honoroit_database_engine: 'sqlite'`)
# - plan your migration to Postgres, as this bridge does not support SQLite anymore (and neither will the playbook in the future).
#
# To use Postgres:
# - adjust your database credentials via the `custom_honoroit_postgres_*` variables
custom_honoroit_database_engine: 'postgres'

custom_honoroit_sqlite_database_path_local: "{{ custom_honoroit_data_path }}/honoroit.db"
custom_honoroit_sqlite_database_path_in_container: "/data/honoroit.db"

custom_honoroit_database_username: 'custom_honoroit'
custom_honoroit_database_password: 'some-password'
custom_honoroit_database_hostname: 'matrix-postgres'
custom_honoroit_database_port: 5432
custom_honoroit_database_name: 'custom_honoroit'

custom_honoroit_database_connection_string: 'postgres://{{ custom_honoroit_database_username }}:{{ custom_honoroit_database_password }}@{{ custom_honoroit_database_hostname }}:{{ custom_honoroit_database_port }}/{{ custom_honoroit_database_name }}?sslmode=disable'

custom_honoroit_appservice_database: "{{
	{
		'sqlite': custom_honoroit_sqlite_database_path_in_container,
		'postgres': custom_honoroit_database_connection_string,
    'none': '',
	}[custom_honoroit_database_engine]
}}"
custom_honoroit_db_dialect: "{{
	{
		'sqlite': 'sqlite3',
		'sqlite3': 'sqlite3',
		'postgres': 'postgres',
    'none': '',
	}[custom_honoroit_database_engine]
}}"


# A list of extra arguments to pass to the container
custom_honoroit_container_extra_arguments: []

# List of systemd services that honoroit.service depends on
custom_honoroit_systemd_required_services_list: ['docker.service']

custom_honoroit_base_path: "{{ matrix_base_data_path }}/honoroit"
custom_honoroit_data_path: "{{ custom_honoroit_base_path }}/data"
