---
- name: Init list
  ansible.builtin.set_fact:
    moncfg_prometheus: []

- name: Load per-host configuration
  ansible.builtin.set_fact:
    moncfg_prometheus: "{{ moncfg_prometheus + lookup('ansible.builtin.file', inventory_dir + '/monitoring/' + item + '.yml') | from_yaml }}"
  with_items: "{{ groups[moncfg_export_group] }}"

- name: Dump full configuration
  ansible.builtin.copy:
    content: "{{ moncfg_prometheus | to_nice_yaml(indent=2, width=999999) }}"
    dest: "{{ inventory_dir }}/monitoring/__all__.yml"
