---
- name: Get public destinations
  ansible.builtin.command: "{{ mrs_discovery_command }}"
  register: raw

- name: Transform public destinations
  set_fact:
    destinations: "{{ raw.stdout_lines[2:(raw.stdout_lines | length) - 1] | map('trim') | list }}"

- name: "Export public destinations (total: {{ destinations | length }})"
  ansible.builtin.uri:
    url: "{{ mrs_discovery_url }}"
    user: "{{ mrs_discovery_login }}"
    password: "{{ mrs_discovery_password }}"
    force_basic_auth: true
    body_format: json
    body: "{{ destinations }}"
    method: POST
    status_code:
      - 202
