---
- name: Clean up docker images and containers
  command: docker system prune -a -f
  when: system_maintenance_docker_prune|bool

- name: Clean up matrix logs older that 7 days
  command: journalctl --vacuum-time=7d
  when: system_maintenance_journalctl_vacuum|bool
