---
- name: Install purge-old-kernels script
  copy:
    src: "{{ role_path }}/files/prune-old-kernels"
    dest: "{{ system_maintenance_pok_path }}"
    mode: 0775
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"

- name: Modify purge-old-kernels to use it with ansible
  replace:
    path: "{{ system_maintenance_pok_path }}"
    mode: 0755
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
    regexp: "^APT_OPTS=$"
    replace: "APT_OPTS=\"-y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew\""

- name: Cleanup old kernels
  command: "{{ system_maintenance_pok_path }} --keep {{ system_maintenance_pok_keep }}"
  environment:
    DEBIAN_FRONTEND: noninteractive
  ignore_errors: yes
