---
# ref: https://github.com/algodelinux/purge-old-kernels/issues/2
- name: Install purge-old-kernels script
  copy:
    src: "{{ role_path }}/files/purge-old-kernels"
    dest: "{{ system_maintenance_pok_path }}"
    mode: 0775
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
  when: system_maintenance_pok|bool

- name: Cleanup old kernels
  command: "{{ system_maintenance_pok_path }} -n -k {{ system_maintenance_pok_keep }} -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew"
  environment:
    DEBIAN_FRONTEND: noninteractive
  ignore_errors: yes
  when: system_maintenance_pok|bool
