---

- block:
    - when: nginx_migration_honoroit_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/honoroit/install.yml"
  tags:
    - setup-all
    - setup-bot-honoroit
    - setup-nginx-proxy
    - install-all
    - install-bot-honoroit
    - install-nginx-proxy

- block:
    - when: nginx_migration_buscarron_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/buscarron/install.yml"
  tags:
    - setup-all
    - setup-bot-buscarron
    - setup-nginx-proxy
    - install-all
    - install-bot-buscarron
    - install-nginx-proxy

- block:
    - when: nginx_migration_languagetool_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/languagetool/install.yml"
  tags:
    - setup-all
    - setup-languagetool
    - setup-nginx-proxy
    - install-all
    - install-languagetool
    - install-nginx-proxy

- block:
    - when: not nginx_migration_languagetool_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/languagetool/uninstall.yml"
  tags:
    - setup-all
    - setup-languagetool

- block:
    - when: nginx_migration_miniflux_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/miniflux/install.yml"
  tags:
    - setup-all
    - setup-miniflux
    - setup-nginx-proxy
    - install-all
    - install-miniflux
    - install-nginx-proxy

- block:
    - when: not nginx_migration_miniflux_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/miniflux/uninstall.yml"
  tags:
    - setup-all
    - setup-miniflux

- block:
    - when: nginx_migration_radicale_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/radicale/install.yml"
  tags:
    - setup-all
    - setup-radicale
    - setup-nginx-proxy
    - install-all
    - install-radicale
    - install-nginx-proxy

- block:
    - when: not nginx_migration_radicale_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/radicale/uninstall.yml"
  tags:
    - setup-all
    - setup-radicale

- block:
    - when: nginx_migration_uptime_kuma_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uptime-kuma/install.yml"
  tags:
    - setup-all
    - setup-radicale
    - setup-nginx-proxy
    - install-all
    - install-radicale
    - install-nginx-proxy

- block:
    - when: not nginx_migration_uptime_kuma_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uptime-kuma/uninstall.yml"
  tags:
    - setup-all
    - setup-radicale
