---

- block:
    - when: nginx_migration_languagetool_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/languagetool/install.yml"
  tags:
    - setup-all
    - setup-languagetool
    - install-all
    - install-languagetool

- block:
    - when: not nginx_migration_languagetool_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/languagetool/uninstall.yml"
  tags:
    - setup-all
    - setup-languagetool

- block:
    - when: nginx_migration_miniflux_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/miniflux/install.yml"
  tags:
    - setup-all
    - setup-miniflux
    - install-all
    - install-miniflux

- block:
    - when: not nginx_migration_miniflux_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/miniflux/uninstall.yml"
  tags:
    - setup-all
    - setup-miniflux

- block:
    - when: nginx_migration_radicale_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/radicale/install.yml"
  tags:
    - setup-all
    - setup-radicale
    - install-all
    - install-radicale

- block:
    - when: not nginx_migration_radicale_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/radicale/uninstall.yml"
  tags:
    - setup-all
    - setup-radicale

- block:
    - when: nginx_migration_uptime_kuma_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uptime-kuma/install.yml"
  tags:
    - setup-all
    - setup-radicale
    - install-all
    - install-radicale

- block:
    - when: not nginx_migration_uptime_kuma_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uptime-kuma/uninstall.yml"
  tags:
    - setup-all
    - setup-radicale
