---

- name: Initialize images vars
  ansible.builtin.set_fact:
    custom_skopeo_sources: "{{ custom_skopeo_static }}"
    custom_skopeo_targets: {}
    custom_skopeo_final: {}

- name: Populate source images list
  ansible.builtin.set_fact:
    custom_skopeo_sources: "{{ custom_skopeo_sources + [lookup('vars', item)] }}"
  loop: "{{ query('varnames', '^.*_(docker|container)_image(_v[0-9]+|_latest)?$') }}"

- name: Unique source images list
  ansible.builtin.set_fact:
    custom_skopeo_sources: "{{ custom_skopeo_sources | unique | sort }}"

- name: Populate target images dict
  ansible.builtin.set_fact:
    custom_skopeo_targets: "{{ custom_skopeo_targets | combine({item: custom_skopeo_target + item | regex_search('/.*')}) }}"
  when: custom_skopeo_ignore_text not in item and item not in custom_skopeo_ignore_images
  loop: "{{ custom_skopeo_sources }}"

- name: Check image status
  ansible.builtin.uri:
    url: "https://{{ custom_skopeo_target }}/v2{{ item | regex_search('\/.*') | replace(':', '/manifests/') }}"
    method: GET
    status_code: [200, 404]
  when: custom_skopeo_ignore_text not in item and item not in custom_skopeo_ignore_images
  failed_when: false
  loop: "{{ custom_skopeo_sources }}"
  register: custom_skopeo_status

- name: Populate final images dict
  ansible.builtin.set_fact:
    custom_skopeo_final: "{{ custom_skopeo_final | combine({item.item: custom_skopeo_targets[item.item]}) }}"
  when: custom_skopeo_ignore_text not in item.item and item.item not in custom_skopeo_ignore_images and (item.status | default(-1) != 200 or item.item.endswith(':latest'))
  loop: "{{ custom_skopeo_status.results }}"

- name: Final list of images to sync
  ansible.builtin.debug:
    msg: "{{ custom_skopeo_final }}"

- name: Sync image between registries
  ansible.builtin.shell: "skopeo copy --all --preserve-digests docker://{{ item.key }} docker://{{ item.value }}"
  loop: "{{ custom_skopeo_final | dict2items }}"
  become: false
  delegate_to: 127.0.0.1
