# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure LanguageTool paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ languagetool_uid }}"
    group: "{{ languagetool_gid }}"
  with_items:
    - "{{ languagetool_base_path }}"
    - "{{ languagetool_data_path }}"

- name: Install n-grams
  ansible.builtin.include_tasks: ngrams.yml
  with_items: "{{ languagetool_ngrams_langs_enabled }}"
  when: languagetool_ngrams_enabled | bool

- name: Ensure LanguageTool labels installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/labels.j2"
    dest: "{{ languagetool_base_path }}/labels"
    mode: 0640
    owner: "{{ languagetool_uid }}"
    group: "{{ languagetool_gid }}"

- name: Ensure LanguageTool container image is pulled
  community.docker.docker_image:
    name: "{{ languagetool_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ languagetool_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else languagetool_container_image_force_pull }}"

- name: Ensure LanguageTool container network is created
  community.general.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ languagetool_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure LanguageTool systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/languagetool.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ languagetool_identifier }}.service"
    mode: 0644
