# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of LanguageTool systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ languagetool_identifier }}.service"
  register: languagetool_service_stat

- when: languagetool_service_stat.stat.exists | bool
  block:
    - name: Ensure LanguageTool is stopped
      ansible.builtin.service:
        name: "{{ languagetool_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure LanguageTool systemd service doesn't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ languagetool_identifier }}.service"
        state: absent

    - name: Ensure LanguageTool path doesn't exist
      ansible.builtin.file:
        path: "{{ languagetool_base_path }}"
        state: absent
