---
- name: Generate honoroit metrics proxying configuration for matrix-nginx-proxy (matrix.DOMAIN/metrics/honoroit)
  ansible.builtin.set_fact:
    matrix_bot_honoroit_nginx_metrics_configuration_block: |
      location /metrics/honoroit {
        {% if matrix_nginx_proxy_enabled | default(False) %}
          {# Use the embedded DNS resolver in Docker containers to discover the service #}
          resolver 127.0.0.11 valid=5s;
          set $backend "matrix-bot-honoroit:8080";
          proxy_pass http://$backend/metrics;
        {% else %}
          return 404 "matrix-nginx-proxy is disabled and no host port was bound to the container, so metrics are unavailable";
        {% endif %}
      }

- name: Register honoroit metrics proxying configuration with matrix-nginx-proxy (matrix.DOMAIN/metrics/honoroit)
  ansible.builtin.set_fact:
    matrix_nginx_proxy_proxy_matrix_metrics_additional_system_location_configuration_blocks: |
      {{
        matrix_nginx_proxy_proxy_matrix_metrics_additional_system_location_configuration_blocks | default([])
        +
        [matrix_bot_honoroit_nginx_metrics_configuration_block]
      }}
