---

- block:
    - when: custom_languagetool_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-languagetool
    - install-all
    - install-languagetool

- block:
    - when: not custom_languagetool_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-languagetool
