---

- ansible.builtin.import_tasks: install.yml
  when: custom_languagetool_enabled|bool
  tags:
    - setup-all
    - setup-languagetool

- ansible.builtin.import_tasks: uninstall.yml
  when: not custom_languagetool_enabled|bool
  tags:
    - setup-all
    - setup-languagetool
