---
- import_tasks: init.yml
  tags:
    - always

- import_tasks: install.yml
  when: custom_radicale_enabled|bool
  tags:
    - setup-all
    - setup-radicale

- import_tasks: uninstall.yml
  when: not custom_radicale_enabled|bool
  tags:
    - setup-all
    - setup-radicale
