---
# Following variables defined in parent roles, like matrix-nginx-proxy or matrix-base,
# but if that role (matrix/nginx-proxy-website) used without parent roles, we should define those vars.
matrix_systemd_path: /etc/systemd/system
matrix_local_bin_path: /usr/local/bin
matrix_user_username: matrix
matrix_user_groupname: matrix
matrix_nginx_proxy_data_path: /matrix/nginx-proxy/data
# that variable does not exists in matrix-nginx-proxy role, value set in "Ensure Matrix nginx-proxy homepage for base domain exists" task
matrix_nginx_proxy_website_path: "{{ matrix_nginx_proxy_data_path }}/matrix-domain"
