---
- include_vars: parent.yml
  when: matrix_nginx_proxy_health_enabled|bool and matrix_local_bin_path is not defined
  tags:
    - setup-all
    - nginx-proxy-health

- name: Ensure matrix-publish-health script installed
  template:
    src: usr-local-bin/matrix-publish-health.j2
    dest: "{{ matrix_local_bin_path }}/matrix-publish-health"
    mode: 0750
  when: matrix_nginx_proxy_health_enabled|bool
  tags:
    - setup-all
    - nginx-proxy-health

- name: Ensure matrix-publish-health units installed
  template:
    src: "systemd/{{ item }}.j2"
    dest: "{{ matrix_systemd_path }}/{{ item }}"
    mode: 0644
  with_items:
    - matrix-publish-health.timer
    - matrix-publish-health.service
  when: matrix_nginx_proxy_health_enabled|bool
  tags:
    - setup-all
    - nginx-proxy-health

- name: Enable and start matrix-publish-health
  systemd:
    name: "{{ item }}"
    daemon_reload: yes
    enabled: yes
    state: started
  with_items:
    - matrix-publish-health.timer
    - matrix-publish-health.service
  when: matrix_nginx_proxy_health_enabled|bool
  tags:
    - setup-all
    - nginx-proxy-health
