---

- block:
    - when: funkwhale_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
  tags:
    - setup-all
    - setup-funkwhale
    - install-all
    - install-funkwhale

- block:
    - when: funkwhale_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-funkwhale
    - install-all
    - install-funkwhale

- block:
    - when: not funkwhale_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-funkwhale


- block:
    - when: funkwhale_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/add_users_auto.yml"
  tags:
    - ensure-funkwhale-users-created
    - ensure-users-created

- block:
    - when: funkwhale_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/add_user_manual.yml"
  tags:
    - funkwhale-add-user
    - funkwhale-add-admin
    - funkwhale-add-superuser
